import {getPublishedPrivacyDocument} from "@/lib/privacy-governance";import {PublishedPrivacyDocument} from "@/components/PublishedPrivacyDocument";import Link from "next/link";import {privacyContacts} from "@/lib/privacy-contacts";import "./privacy.css";
export const metadata={robots:{index:false,follow:false},title:"Kişisel Verilerin Korunması",description:"Q-GANG kişisel veri aydınlatması ve gizlilik düzeni"};
const categories=[
 ["Hesap ve kimlik","Kullanıcının seçtiği kullanıcı adı, rumuz, e-posta ve sağlayıcı hesap kimliği","Giriş, hesap eşleştirme ve güvenlik; gerçek ad ve soyadı talep edilmez. Google oturum/kimlik verilerinde ad bilgisi iletebilir; profil kullanıcı adına veya Google bağlı hesap etiketine kopyalanmaz. Önceki kayıtlarda ad bilgisi bulunabilir. E-posta genel profilde yayımlanmaz."],
 ["Profil","Biyografi, avatar, banner ve görünürlük tercihi","Profil sunumu; yüklenen görsellerin bağlantısı herkese açık olabilir."],
 ["Üyelik","Kabul tarihi, rütbe, görev, mühür ve eski üye eşleşmesi","Üyelik ve topluluk işleyişi; doğrulama dayanakları yetkili alanlarda tutulur."],
 ["Doğum bilgisi","Doğum tarihi ve görünürlük tercihi","Profil ve doğum günü hatırlatmaları; diğer kişilere tercih kadar bilgi gösterilir."],
 ["Yayın ve yorum","Metin, yazar ve yayın tarihi","İçerik yayımlama ve etkileşim; yayımlanmış yayınlar, duyurular ve icra kararlarının metinleri ziyaretçilerce görülebilir. Taslaklar, özel profiller ve yönetim kayıtları bu kapsamda açılmaz."],
 ["Rozet","Kazanım, atama ve düzeltme kayıtları","Kazanımların gösterimi ve atama denetimi; ayrıntılı gerekçeler yetkililerle sınırlıdır."],
 ["Disiplin ve başvuru","Karar, savunma, delil, itiraz ve talepler","Topluluk düzeni, hakların korunması ve başvuru değerlendirmesi; gerekli kişilerle sınırlı erişim."],
 ["Bütçe","Katkı ve mali işlem kayıtları","Bütçe takibi ve hesap verilebilirlik; anonimlik tercihi gözetilir. Yetkili kişiler mali defter PDF çıktısını indirebilir."],
 ["Aster ve güvenlik","Konuşma, oturum ve teknik işlem kayıtları","Talep edilen yardım ve güvenli işletim; özel üye kayıtları genel bilgi kaynağına dönüştürülmez."]
];
export default async function Privacy(){const [document,contacts]=await Promise.all([getPublishedPrivacyDocument("aydinlatma"),privacyContacts()]);if(document)return <PublishedPrivacyDocument document={document} contacts={contacts}/>;return <main className="privacyPage"><header><h1>Kişisel Verilerin Korunması</h1><p><strong>Yayım öncesi taslak:</strong> Saklama süreleri ve aktarım düzeni tamamlanacaktır.</p><p>Veri sorumlusu: Ömer Faruk Karabul. Q-GANG hesabı ve topluluk faaliyetleri kapsamında işlenen kişisel veriler hakkında bilgilendirme.</p><nav className="privacyActions"><Link className="qgAction" href="/gizlilik/verilerim">Gizlilik ve Verilerim</Link><Link className="qgAction" href="/gizlilik/cerezler">Çerez ve dış içerik bilgisi</Link><Link className="qgAction" href="/gizlilik/saklama">Saklama ve imha</Link><Link className="qgAction" href="/">Ana sayfa</Link></nav></header>
 <section><h2>Veri kategorileri ve amaçlar</h2><div className="privacyTable"><table><thead><tr><th>Kategori</th><th>Kapsam</th><th>Amaç ve erişim</th></tr></thead><tbody>{categories.map(([a,b,c])=><tr key={a}><th>{a}</th><td>{b}</td><td>{c}</td></tr>)}</tbody></table></div></section>
 <section><h2>Toplama yöntemi ve işleme sebepleri</h2><p>Veriler; giriş sağlayıcısından, doldurduğun formlardan, yayımladığın içeriklerden, topluluk kayıtlarından ve sistem işlemlerinden elektronik ortamda elde edilir. İşleme faaliyetinin niteliğine göre hizmet ilişkisinin kurulması veya yürütülmesi, bir hakkın tesisi, kullanılması veya korunması, hukuki yükümlülük ve temel haklarını gözeten meşru menfaat değerlendirilir. Açık rıza gerektiren faaliyetler ayrıca ele alınır; bu metni görmek veya siteye giriş yapmak açık rıza yerine geçmez.</p></section>
 <section><h2>Alıcılar ve yurt dışındaki hizmetler</h2><p>Q-GANG; kimlik doğrulama için Google, veritabanı ve depolama için Supabase, barındırma için Vercel hizmetlerini kullanır. Bu hizmetlerin işletimi yurt dışında veri işlenmesini içerebilir. Aster etkinleştirilirse kullanılan sağlayıcı ve gönderilen veri kapsamı ayrıca açıklanır. Dış görsel veya video sağlayıcıları içerik yüklenirken bağlantı bilgilerini alabilir.</p><p>Sağlayıcı sözleşmeleri ve uygulanacak yurt dışı aktarım güvencesi için inceleme sürmektedir. Bu bilgilendirme, tamamlanmış bir aktarım uygunluğu beyanı değildir.</p></section>
 <section><h2>Disiplin başvurularına erişim</h2><p>Başvuran kendi şikâyet ve itirazının durumunu, kendi itirazına verilen yanıtı görebilir. Diğer başvuranların kayıtları kişisel başvuru ekranında gösterilmez; yetkili inceleme erişimi görev ve izinlerle sınırlıdır.</p></section><section><h2>Saklama, silme ve erişim</h2><p>Veriler amaç için gereken süreyle sınırlı tutulmalıdır. Hesap kapatma, bütün verilerin otomatik silinmesi anlamına gelmez. Silme başvurusu kategori bazında değerlendirilir; saklanması gereken kayıtlar için gerekçe ve süre açıklanır. Kurumsal tarihçe tek başına sınırsız kişisel veri saklama gerekçesi değildir. Kategori bazlı saklama süreleri ve sağlayıcı yedeklerinin imha takvimi kesinleştirilme aşamasındadır.</p></section>
 <section><h2>Hakların ve başvuru</h2><p>Kişisel verilerinin işlenip işlenmediğini öğrenme, bilgi isteme, amaç ve alıcıları öğrenme, düzeltme, şartları varsa silme veya yok etme, işlemlerin alıcılara bildirilmesini isteme, yalnız otomatik analiz sonucu aleyhine çıkan sonuca itiraz ve hukuka aykırı işleme nedeniyle zararın giderilmesini talep etme hakların vardır.</p><p>Oturum açarak Gizlilik ve Verilerim alanından başvuru oluşturabilir ve yanıtını takip edebilirsin. Başvurunu aşağıdaki adreslerden herhangi birine de iletebilirsin. Her iki adrese birden göndermen gerekmez. Başvurunun niteliğine göre güvenli ve ölçülü kimlik doğrulaması istenebilir.</p><div className="privacyActions">{contacts.map(email=><a className="qgAction" key={email} href={"mailto:"+email}>{email}</a>)}</div></section></main>}
