
import {Button,Select,Textarea} from "@/components/ui/Primitives";
import Link from "next/link";import {getPrivacyCapabilities} from "@/lib/privacy-governance";import {redirect} from "next/navigation";
import {AppShell} from "@/components/AppShell";import {createClient,getCurrentUser} from "@/lib/supabase/server";
import {privacyKinds,privacyStatuses} from "@/lib/privacy";import "../privacy.css";
export const dynamic="force-dynamic";export const metadata={title:"Gizlilik ve Verilerim"};
export default async function MyPrivacy({searchParams}:{searchParams:Promise<{error?:string;saved?:string}>}){
 const user=await getCurrentUser();if(!user)redirect("/login?next=/gizlilik/verilerim");const q=await searchParams,s=await createClient(),caps=await getPrivacyCapabilities();
 const [{data:requests,error},{data:me}]=await Promise.all([s.from("privacy_requests").select("id,kind,detail,status,response,created_at,due_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(30),s.from("profiles").select("role").eq("id",user.id).maybeSingle()]);
 return <AppShell right={false}><main className="privacyPage"><header><h1>Gizlilik ve Verilerim</h1><p>Görünürlük tercihlerin ve kişisel veri başvuruların.</p></header><nav className="privacyActions"><Link className="qgAction" href="/profil">Profil tercihlerini düzenle</Link><Link className="qgAction" href="/gizlilik">Aydınlatma metni</Link>{caps.requests&&<Link className="qgAction" href="/gizlilik/yonetim">Başvuruları yönet</Link>}{caps.documents&&<Link className="qgAction" href="/gizlilik/yonetim/metinler">Gizlilik metinleri</Link>}</nav>
 {(q.error||error)&&<p role="alert">İşlem tamamlanamadı. Açık başvurunu ve form bilgilerini kontrol et; sorun sürerse tekrar dene.</p>}{q.saved&&<p role="status">Başvurun kaydedildi.</p>}
 <section><h2>Verilerimin kopyası</h2><p>Temel hesap, üyelik, yayın ve kendi yorum kayıtlarını JSON olarak indirebilirsin. Bu dosya bütün sistem kayıtlarının dökümü değildir; kapsam dışındaki kayıtlar için erişim başvurusu oluşturabilirsin.</p><form action="/api/privacy/export" method="post"><Button level="secondary" className="qgAction" type="submit">Temel verilerimi indir</Button></form></section><section><h2>Başvuru oluştur</h2><p>Hesap kapatma üyelikten ayrılma veya bütün kayıtların silinmesi anlamına gelmez. Silme talepleri veri kategorilerine göre değerlendirilir. Bu formda kimlik belgesi, sağlık bilgisi veya üçüncü kişilere ait hassas veriler paylaşma.</p>
 <form action="/api/privacy/request" method="post"><label>Başvuru türü<Select name="kind">{Object.entries(privacyKinds).map(([v,label])=><option key={v} value={v}>{label}</option>)}</Select></label><label>Talebin<Textarea name="detail" minLength={10} maxLength={3000} required rows={5}/></label><Button level="secondary" className="qgAction" type="submit">Başvuruyu gönder</Button></form></section>
 <section><h2>Başvurularım</h2>{!error&&!requests?.length&&<p>Henüz başvurun bulunmuyor.</p>}{requests?.map(r=><article key={r.id}><h3>{privacyKinds[r.kind as keyof typeof privacyKinds]}</h3><small>{privacyStatuses[r.status as keyof typeof privacyStatuses]} · {new Date(r.created_at).toLocaleDateString("tr-TR",{timeZone:"Europe/Istanbul"})}</small><p>{r.detail}</p>{r.response&&<p><strong>Yanıt:</strong> {r.response}</p>}</article>)}</section></main></AppShell>;
}
