import {QGIcon} from "@/components/QGIcon";import {CodexComposer} from "@/components/CodexComposer";import {revalidatePath} from "next/cache";import {brandTheme} from "@/config/brand-theme";import {redirect} from "next/navigation";import {AppShell} from "@/components/AppShell";import {createClient,getCurrentUser} from "@/lib/supabase/server";import {canManage} from "@/lib/roles";import {pageMeta} from "@/lib/design";export const dynamic="force-dynamic";export const metadata=pageMeta.rules;
const SECTIONS=[["01","TEMEL KURALLAR"],["02","TOPLULUK DÜZENİ"],["03","YÖNETİM VE ORGANİZASYON"],["04","YAYIM VE İÇERİK DÜZENİ"],["05","DİSİPLİN DÜZENİ"],["06","HAZİNE VE MALİ DÜZEN"],["07","KODEKS'İN DEĞİŞTİRİLMESİ VE YÜRÜRLÜĞÜ"]].map(([number,title])=>({number,title}));
function cleanHtml(v:string){return v.replace(/<script[\s\S]*?<\/script>/gi,"").replace(/\son\w+="[^"]*"/gi,"").replace(/javascript:/gi,"").trim()}
async function addRule(formData:FormData){"use server";const s=await createClient();const user=await getCurrentUser();if(!user)redirect("/login");const {data:me}=await s.from("profiles").select("role").eq("id",user.id).single();if(!canManage(me?.role))return;const title=String(formData.get("title")||"").trim(),body=cleanHtml(String(formData.get("body")||"")),number=String(formData.get("number")||"").trim(),section=String(formData.get("section_number")||"").trim(),mode=String(formData.get("effective_mode")||"now"),scheduled=String(formData.get("effective_at")||"").trim();if(!title||!number||!section)return;const effectiveAt=mode==="scheduled"&&scheduled?new Date(scheduled).toISOString():new Date().toISOString();await s.from("regulations").insert({title,body,number,section_number:section,kind:String(formData.get("kind")||"KURAL"),status:"yururlukte",effective_at:effectiveAt,change_reason:String(formData.get("reason")||"İlk yayım").trim()||"İlk yayım",created_by:user.id});revalidatePath("/rules");revalidatePath("/")}
export default async function Rules({searchParams}:{searchParams:Promise<{q?:string;status?:string;rule?:string;section?:string}>}){const q=await searchParams;const term=(q.q||"").trim().toLowerCase(),status=q.status||"all";const s=await createClient();const user=await getCurrentUser();const [{data:rules},{data:me}]=await Promise.all([s.from("regulations").select("id,title,body,kind,number,section_number,status,published_at,effective_at,revision").order("number").limit(200),user?s.from("profiles").select("role").eq("id",user.id).single():Promise.resolve({data:null})]);const all=rules??[],list=all.filter((r:any)=>(status==="all"||(status==="active"?r.status==="yururlukte":r.status!=="yururlukte"))&&(!q.section||r.section_number===q.section)&&(!term||`${r.title} ${r.body||""} ${r.number||""}`.toLowerCase().includes(term))),manage=canManage(me?.role),active=all.filter((r:any)=>r.status==="yururlukte").length,selected=list.find((r:any)=>r.id===q.rule)||list[0];return <AppShell right={false}><main className="codexV2">
<section className="codexScene codexHeroUnified roomScene" style={{backgroundImage:`linear-gradient(90deg,rgba(4,3,2,.82),rgba(4,3,2,.38) 48%,rgba(4,3,2,.18)),url(${brandTheme.rooms.codex})`}}><h1>Kurallar</h1><p>Q-GANG düzeninin yürürlükteki hükümleri, ilkeleri ve kararları.</p><div className="codexSceneMark"><QGIcon name="rules"/></div></section>
<section className="codexToolbar"><div><b><QGIcon name="document"/> {all.length}</b><span>TOPLAM HÜKÜM</span></div><div><b><QGIcon name="seal"/> {active}</b><span>YÜRÜRLÜKTE</span></div><div><b><QGIcon name="archive"/> {all.length-active}</b><span>ARŞİV</span></div><form action="/rules"><input name="q" defaultValue={q.q||""} placeholder="Hüküm ara…"/><select name="status" defaultValue={status}><option value="all">Tümü</option><option value="active">Yürürlükte</option><option value="archive">Arşiv</option></select></form></section>
<nav className="codexSectionTabs" aria-label="Kodeks bölümleri"><a className={!q.section?"active":""} href="/rules">TÜMÜ</a>{SECTIONS.map(x=><a className={q.section===x.number?"active":""} key={x.number} href={`/rules?section=${x.number}`}>§ {x.number}<span>{x.title}</span></a>)}</nav>
<div className="codexWorkspace"><section className="codexIndex"><header><QGIcon name="list"/> HÜKÜMLER</header>{list.length?list.map((r:any)=><a href={`/rules?rule=${r.id}${q.section?`&section=${q.section}`:""}`} className={selected?.id===r.id?"selected":""} key={r.id}><b>§ {r.number}</b><div><strong>{r.title}</strong><small>{r.kind}</small></div><em>{r.status==="yururlukte"?"YÜRÜRLÜKTE":"ARŞİV"}</em></a>):<div className="codexIndexEmpty">Bu görünümde hüküm bulunmuyor.</div>}</section>
<section className="codexDetail"><header><span><QGIcon name="document"/> HÜKÜM DETAYI</span><b><QGIcon name="status"/> {selected?.status==="yururlukte"?"YÜRÜRLÜKTE":"MÜHÜRLENMEYİ BEKLİYOR"}</b></header>{selected?<div className="codexPaper"><span>§ {selected.number}</span><h2>{selected.title}</h2><small>{selected.kind} · SÜRÜM {selected.revision||1}</small><div className="codexBody" dangerouslySetInnerHTML={{__html:selected.body||"Bu hüküm için açıklama girilmemiş."}}/><footer>Yürürlük · {selected.effective_at?new Date(selected.effective_at).toLocaleDateString("tr-TR"):"—"}</footer></div>:<div className="codexPaper emptyPaper"><span>Q-GANG</span><h2>KODEKS</h2><small>SÜRÜM 1.0</small><p>Bir bölüm seçerek yürürlükteki hükümleri inceleyebilirsiniz.</p><div className="codexWax"><img src={brandTheme.emblem} alt="Q-GANG mührü"/></div></div>}</section></div>
{manage&&<CodexComposer action={addRule} sections={SECTIONS}/>}
</main></AppShell>}