"use client";
import {Button} from "@/components/ui/Primitives";

import {useMemo,useState,useTransition} from "react";
import {PERMISSIONS,ROLE_LABEL,type AppRole} from "@/lib/roles";
type Row={role:AppRole;permission:string;enabled:boolean};
const ROLES:[AppRole,string][]=[["founder","LİDER"],["admin","VEKİLHARÇ"],["moderator","KAPTAN"],["creator","TEĞMEN"],["member","ÜYE"],["guest","PLATFORM"]];
const DESC:Record<string,string>={"events.view":"Topluluk etkinlikleri ve arşivini görüntüler.","events.propose":"İncelenmek üzere etkinlik önerir.","events.manage":"Taslak oluşturur, etkinlikleri düzenler ve önerileri inceler.","events.publish":"Düzenleme yetkisiyle birlikte yayımlar, tamamlar veya iptal eder.","events.attendance":"Gerçekleşen katılımı doğrular ve düzeltir.","events.archive":"Tarihsel kayıt aktarımını ve kimlik eşleştirmesini yönetir.","events.settings":"Tür adlarını, açıklamalarını ve sıralamasını düzenler.","members.view":"Topluluk ve üye kayıtlarını görür.","members.manage":"Üyelik ve izin verilen rütbe işlemlerini yönetir.","members.delete":"Uygun kullanıcı hesabını kalıcı siler.","discipline.view":"Disiplin sicili ve arşivini görür.","discipline.issue":"Yeni yaptırım kararı oluşturur.","discipline.review":"Karar ve itiraz incelemesi yapar.","announcements.publish":"Duyuru ve karar yayımlar.","budget.view":"Hazine kayıtlarını görüntüler.","budget.manage":"Gelir/gider oluşturur ve yönetir.","design.manage":"Tasarım Merkezi ayarlarını değiştirir.","access.manage":"Erişim Merkezi yetki matrisini yönetir.","maintenance.access":"Bakım erişimi kişi bazında Sistem Merkezi’nden verilir.","announcements.delete":"Duyuruyu kalıcı olarak siler.","budget.delete":"Sehven oluşmuş, geri alınmamış bütçe kaydını siler.","publications.view":"Yayın kayıtlarını görüntüler.","publications.write":"Yayın oluşturur ve düzenler.","publications.publish":"Yayını kamuya açar veya yayından kaldırır.","publications.delete":"Yayını kalıcı olarak siler."};
const DEFAULTS:Record<AppRole,string[]>={
 founder:PERMISSIONS.map(([p])=>p),
 admin:["events.view","events.propose","events.manage","events.publish","events.attendance","events.archive","events.settings","members.view","members.manage","members.delete","discipline.view","discipline.issue","discipline.review","announcements.publish","announcements.delete","budget.view","budget.manage","budget.delete","design.manage","publications.view","publications.write","publications.publish","publications.delete"],
 moderator:["events.view","events.propose","events.manage","events.publish","events.attendance","members.view","members.manage","discipline.view","discipline.issue","announcements.publish","budget.view","publications.view","publications.write"],
 creator:["events.view","events.propose","members.view","discipline.view","budget.view","publications.view","publications.write"],
 member:["events.view","events.propose","members.view","publications.view"],
 guest:[]
};
function unavailable(role:AppRole,p:string){return role==="founder"||p==="maintenance.access"||p==="access.manage"||(p==="discipline.issue"&&(role==="creator"||role==="member"||role==="guest"))||(p==="discipline.review"&&(role==="moderator"||role==="creator"||role==="member"||role==="guest"))}
export function AccessMatrixEditor({rows}:{rows:Row[]}){
 const initial=useMemo(()=>{const s=new Set<string>();rows.filter(x=>x.enabled).forEach(x=>s.add(x.role+":"+x.permission));PERMISSIONS.forEach(([p])=>s.add("founder:"+p));return s},[rows]);
 const[state,setState]=useState<Set<string>>(()=>new Set(initial)),[saved,setSaved]=useState<Set<string>>(()=>new Set(initial)),[notice,setNotice]=useState(""),[pending,start]=useTransition();
 const dirty=useMemo(()=>state.size!==saved.size||[...state].some(x=>!saved.has(x)),[state,saved]);
 function toggle(role:AppRole,p:string){
  if(unavailable(role,p))return;setNotice("");
  setState(prev=>{
   const n=new Set(prev),k=role+":"+p,off=n.has(k);off?n.delete(k):n.add(k);
   if(p==="events.view"&&off){for(const[ep]of PERMISSIONS){if(ep.startsWith("events."))n.delete(role+":"+ep)}}
   if(p.startsWith("events.")&&p!=="events.view"&&!off)n.add(role+":events.view");
   return n;
  });
 }
 function resetSaved(){setState(new Set(saved));setNotice("")}
 function resetDefaults(){if(!confirm("Q-GANG varsayılan yetki matrisi yüklensin mi? Değişiklikler Onayla denene kadar kaydedilmez."))return;const n=new Set<string>();for(const[r]of ROLES)for(const[p]of PERMISSIONS){const k=r+":"+p;if(r==="founder"||(unavailable(r,p)?saved.has(k):DEFAULTS[r].includes(p)))n.add(k)}setState(n);setNotice("Varsayılan matris hazır. Kaydetmek için değişiklikleri onayla.")}
 function save(){const changes:{role:AppRole;permission:string;enabled:boolean}[]=[];for(const[role]of ROLES)for(const[p]of PERMISSIONS){if(role==="founder"||p==="maintenance.access")continue;const k=role+":"+p,a=saved.has(k),b=state.has(k);if(a!==b)changes.push({role,permission:p,enabled:b})}if(!changes.length)return;start(async()=>{setNotice("");try{const r=await fetch("/api/control/access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({changes})});const body=(await r.json().catch(()=>null)) as {error?:string;rows?:Row[]}|null;if(!r.ok){setNotice(body?.error??"Yetki değişiklikleri kaydedilemedi.");return}const next=body?.rows?new Set(body.rows.filter(x=>x.enabled).map(x=>x.role+":"+x.permission)):new Set(state);PERMISSIONS.forEach(([p])=>next.add("founder:"+p));setState(next);setSaved(new Set(next));setNotice("Yetki matrisi güncellendi.")}catch{setNotice("Bağlantı kurulamadı. Taslak korunuyor; tekrar onaylayabilirsin.")}})}
 return <section className="accessMatrix panel"><header><div><span className="kicker">YETKİ MATRİSİ</span><h2>Rütbe × Yetki</h2></div><small>Değişiklikler önce taslak olarak tutulur; yalnızca onayladığında sisteme uygulanır.</small></header>{notice&&<div className={"notice "+(notice.includes("güncellendi")?"success":"")}>{notice}</div>}<p className="accessScrollHint">Tüm rütbeleri görmek için tabloyu yatay kaydır.</p><div className="accessTable" role="region" aria-label="Rütbe ve yetki matrisi" tabIndex={0}><div className="accessRow accessHead"><b>YETKİ</b>{ROLES.map(([r,l])=><b key={r}>{l}</b>)}</div>{PERMISSIONS.map(([p,label])=><div className="accessRow" key={p}><div className="permissionCopy"><strong>{label}</strong><small>{DESC[p]}</small><code>{p}</code></div>{ROLES.map(([role])=>{const on=state.has(role+":"+p),na=unavailable(role,p);return <button type="button" key={role} disabled={na||pending} onClick={()=>toggle(role,p)} className={"permissionSwitch "+(na?"permissionNA":on?"permissionOn":"permissionOff")+(on!==saved.has(role+":"+p)?" permissionChanged":"")} aria-pressed={on} aria-label={ROLE_LABEL[role]+" "+label}><i/>{p==="maintenance.access"?"—":on?"AÇIK":"KAPALI"}</button>})}</div>)}</div><footer className="accessActions"><Button level="secondary" type="button" onClick={resetDefaults} disabled={pending}>VARSAYILANLARA DÖN</Button><span/><Button level="secondary" type="button" onClick={resetSaved} disabled={!dirty||pending}>DEĞİŞİKLİKLERİ İPTAL ET</Button><Button level="primary" type="button" className="" onClick={save} disabled={!dirty||pending}>{pending?"KAYDEDİLİYOR…":"DEĞİŞİKLİKLERİ ONAYLA"}</Button></footer></section>
}