"use client";
import {useMemo,useState,useTransition} from "react";
import {PERMISSIONS,ROLE_LABEL,type AppRole} from "@/lib/roles";
type Row={role:AppRole;permission:string;enabled:boolean};
const ROLES:[AppRole,string][]=[["founder","LİDER"],["admin","VEKİLHARÇ"],["moderator","KAPTAN"],["creator","TEĞMEN"],["member","ÜYE"],["guest","PLATFORM"]];
const DESC:Record<string,string>={"members.view":"Topluluk ve üye kayıtlarını görür.","members.manage":"Üyelik ve izin verilen rütbe işlemlerini yönetir.","members.delete":"Uygun kullanıcı hesabını kalıcı siler.","discipline.view":"Disiplin sicili ve arşivini görür.","discipline.issue":"Yeni yaptırım kararı oluşturur.","discipline.review":"Karar ve itiraz incelemesi yapar.","announcements.publish":"Duyuru ve karar yayımlar.","budget.view":"Hazine kayıtlarını görüntüler.","budget.manage":"Gelir/gider oluşturur ve yönetir.","design.manage":"Tasarım Merkezi ayarlarını değiştirir.","access.manage":"Erişim Merkezi yetki matrisini yönetir.","maintenance.access":"Bakım erişimi kişi bazında Sistem Merkezi’nden verilir.","announcements.delete":"Duyuruyu kalıcı olarak siler.","budget.delete":"Sehven oluşmuş, geri alınmamış bütçe kaydını siler.","publications.view":"Yayın kayıtlarını görüntüler.","publications.write":"Yayın oluşturur ve düzenler.","publications.publish":"Yayını kamuya açar veya yayından kaldırır.","publications.delete":"Yayını kalıcı olarak siler."};
const DEFAULTS:Record<AppRole,string[]>={
 founder:PERMISSIONS.map(([p])=>p),
 admin:["members.view","members.manage","members.delete","discipline.view","discipline.issue","discipline.review","announcements.publish","announcements.delete","budget.view","budget.manage","budget.delete","design.manage","access.manage","publications.view","publications.write","publications.publish","publications.delete"],
 moderator:["members.view","members.manage","discipline.view","discipline.issue","announcements.publish","budget.view","publications.view","publications.write"],
 creator:["members.view","discipline.view","budget.view","publications.view","publications.write"],
 member:["members.view","publications.view"],
 guest:[]
};
function unavailable(role:AppRole,p:string){return role==="founder"||p==="maintenance.access"||(p==="access.manage"&&role!=="founder"&&role!=="admin")||(p==="discipline.issue"&&(role==="creator"||role==="member"||role==="guest"))||(p==="discipline.review"&&(role==="moderator"||role==="creator"||role==="member"||role==="guest"))}
export function AccessMatrixEditor({rows}:{rows:Row[]}){
 const initial=useMemo(()=>{const s=new Set<string>();rows.filter(x=>x.enabled).forEach(x=>s.add(x.role+":"+x.permission));PERMISSIONS.forEach(([p])=>s.add("founder:"+p));return s},[rows]);
 const[state,setState]=useState(new Set(initial)),[saved,setSaved]=useState(new Set(initial)),[notice,setNotice]=useState(""),[pending,start]=useTransition();
 const dirty=useMemo(()=>state.size!==saved.size||[...state].some(x=>!saved.has(x)),[state,saved]);
 function toggle(role:AppRole,p:string){if(unavailable(role,p))return;setNotice("");setState(prev=>{const n=new Set(prev),k=role+":"+p;n.has(k)?n.delete(k):n.add(k);return n})}
 function resetSaved(){setState(new Set(saved));setNotice("")}
 function resetDefaults(){if(!confirm("Q-GANG varsayılan yetki matrisi yüklensin mi? Değişiklikler Onayla denene kadar kaydedilmez."))return;const n=new Set<string>();for(const[r]of ROLES)for(const p of DEFAULTS[r])n.add(r+":"+p);setState(n);setNotice("Varsayılan matris hazır. Kaydetmek için değişiklikleri onayla.")}
 function save(){const changes:{role:AppRole;permission:string;enabled:boolean}[]=[];for(const[role]of ROLES)for(const[p]of PERMISSIONS){if(role==="founder"||p==="maintenance.access")continue;const k=role+":"+p,a=saved.has(k),b=state.has(k);if(a!==b)changes.push({role,permission:p,enabled:b})}if(!changes.length)return;start(async()=>{setNotice("");const r=await fetch("/api/control/access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({changes})});const body=await r.json().catch(()=>({}));if(!r.ok){setNotice(body.error||"Yetki değişiklikleri kaydedilemedi.");return}setSaved(new Set(state));setNotice("Yetki matrisi güncellendi.")})}
 return <section className="accessMatrix panel"><header><div><span className="kicker">YETKİ MATRİSİ</span><h2>Rütbe × Yetki</h2></div><small>Değişiklikler önce taslak olarak tutulur; yalnızca onayladığında sisteme uygulanır.</small></header>{notice&&<div className={"notice "+(notice.includes("güncellendi")?"success":"")}>{notice}</div>}<p className="accessScrollHint">Tüm rütbeleri görmek için tabloyu yatay kaydır.</p><div className="accessTable"><div className="accessRow accessHead"><b>YETKİ</b>{ROLES.map(([r,l])=><b key={r}>{l}</b>)}</div>{PERMISSIONS.map(([p,label])=><div className="accessRow" key={p}><div className="permissionCopy"><strong>{label}</strong><small>{DESC[p]}</small><code>{p}</code></div>{ROLES.map(([role])=>{const on=state.has(role+":"+p),na=unavailable(role,p);return <button type="button" key={role} disabled={na} onClick={()=>toggle(role,p)} className={"permissionSwitch "+(na?"permissionNA":on?"permissionOn":"permissionOff")+(on!==saved.has(role+":"+p)?" permissionChanged":"")} aria-label={ROLE_LABEL[role]+" "+label}><i/>{p==="maintenance.access"?"—":on?"AÇIK":"KAPALI"}</button>})}</div>)}</div><footer className="accessActions"><button type="button" onClick={resetDefaults} disabled={pending}>VARSAYILANLARA DÖN</button><span/><button type="button" onClick={resetSaved} disabled={!dirty||pending}>DEĞİŞİKLİKLERİ İPTAL ET</button><button type="button" className="primary" onClick={save} disabled={!dirty||pending}>{pending?"KAYDEDİLİYOR…":"DEĞİŞİKLİKLERİ ONAYLA"}</button></footer></section>
}