
import {Input,Textarea,Button,Select} from "@/components/ui/Primitives";
import {MemberPicker} from "@/components/MemberPicker";
import {createClient} from "@/lib/supabase/server";
import {redirect} from "next/navigation";
async function save(form:FormData){"use server";const s=await createClient();const {error}=await s.rpc("save_badge_definition",{p_id:String(form.get("id")||"")||null,p_slug:String(form.get("slug")||""),p_name:String(form.get("name")||""),p_description:String(form.get("description")||""),p_type:String(form.get("norm_type")||"discretionary"),p_active:form.get("active")==="on",p_reason:String(form.get("reason")||"")});redirect("/topluluk?manage=1&badge_catalog="+(error?"error":"saved"));}
async function saveCondition(form:FormData){"use server";const s=await createClient();const slug=String(form.get("slug")||"");const rule=slug==="ilk-halka"?{kind:"member-login-cutoff",until:String(form.get("until")),timezone:"Europe/Istanbul"}:slug==="kidem-nisani"?{kind:"manual-tenure",days:Number(form.get("days"))}:{kind:"published-work",count:Number(form.get("count"))};const {error}=await s.rpc("set_badge_condition",{p_id:String(form.get("id")),p_rule:rule,p_reason:String(form.get("reason")||"")});redirect("/topluluk?manage=1&badge_catalog="+(error?"error":"saved"));}
const labels:Record<string,string>={historical:"Tarihsel nişan",achievement:"Kazanım nişanı",discretionary:"Takdir nişanı",high_honor:"Yüksek onur nişanı"};
export async function BadgeManagement({role,members}:{role:string;members:{id:string;display_name:string;membership_status:string}[]}){
 const s=await createClient();const [{data:catalog},{data:manager}]=await Promise.all([s.from("badges").select("*").order("sort_order"),s.rpc("badge_manager_data")]);
 return <section className="managementPanel badgeManagement"><h2>Rozet Kataloğu ve Geçmiş</h2><p>Rozetler rütbe, görev veya erişim sağlamaz. Kaptan teklifleri yönetimin yazılı iletişim kanalından alınır.</p><details><summary>Rozet kataloğunu incele</summary>{(catalog??[]).map(b=><article className="badgeCatalogRow" key={b.id}>{b.image_url&&<img src={b.image_url} alt=""/>}<div><h3>{b.name}</h3><small>{labels[b.norm_type]} · {b.active?"Yeni atamalara açık":"Emekli"}</small><p>{b.description}</p>{role==="founder"&&<details><summary>Tanımı düzenle / emekliye ayır</summary><form action={save}><input type="hidden" name="id" value={b.id}/><input type="hidden" name="slug" value={b.slug}/><input type="hidden" name="norm_type" value={b.norm_type}/><label>Ad<Input name="name" defaultValue={b.name} required maxLength={100}/></label><label>Mahiyet<Textarea name="description" defaultValue={b.description} required maxLength={2000}/></label><label><input type="checkbox" name="active" defaultChecked={b.active}/> Yeni kazanım ve atamalara açık</label><label>Gerekçe<Input name="reason" required minLength={3} maxLength={2000}/></label><Button type="submit" level="secondary">KAYDET</Button></form>{["ilk-halka","kidem-nisani","muellif"].includes(b.slug)&&<form action={saveCondition}><input type="hidden" name="id" value={b.id}/><input type="hidden" name="slug" value={b.slug}/><b>Temel kazanım koşulu</b>{b.slug==="ilk-halka"?<><label>Bitiş (bu gün dahil değil)<Input name="until" type="date" required defaultValue={b.rule?.until}/></label></>:b.slug==="kidem-nisani"?<label>Yönetimin değerlendireceği kıdem süresi (gün)<Input name="days" type="number" min={1} max={36500} required defaultValue={b.rule?.days}/></label>:<label>Yayımlanmış eser sayısı<Input name="count" type="number" min={1} max={10000} required defaultValue={b.rule?.count}/></label>}<label>Koşul değişikliği gerekçesi<Input name="reason" required minLength={3} maxLength={2000}/></label><p>Geçmiş kazanımlar korunur. Değişiklik yönergeyle uyumlu olmalıdır.</p><Button type="submit" level="secondary">KOŞULU KAYDET</Button></form>}</details>}</div></article>)}</details>
 {role==="founder"&&<><details><summary>Yeni takdir / yüksek onur nişanı oluştur</summary><form action={save}><label>Kod<Input name="slug" required pattern="[a-z0-9][a-z0-9-]{2,60}"/></label><label>Ad<Input name="name" required maxLength={100}/></label><label>Mahiyet<Textarea name="description" required maxLength={2000}/></label><label>Tür<Select name="norm_type"><option value="discretionary">Takdir nişanı</option><option value="high_honor">Yüksek onur nişanı</option></Select></label><label><input name="active" type="checkbox" defaultChecked/> Yeni atamalara açık</label><Input aria-label="İşlem gerekçesi" name="reason" required minLength={3} placeholder="Oluşturma gerekçesi"/><Button type="submit" level="secondary">OLUŞTUR</Button></form></details><details><summary>Kayıtlara dayalı kazanım tanı</summary><form action="/api/badges" method="post"><input type="hidden" name="action" value="recognize"/><MemberPicker name="target_id" label="Üye / hesap seç" scope="badges"/><Select aria-label="Rozet" name="badge_id" required>{(catalog??[]).filter(b=>b.active&&["historical","achievement"].includes(b.norm_type)).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select><Input aria-label="İşlem gerekçesi" name="reason" required minLength={3} placeholder="Tanıma gerekçesi"/><Textarea aria-label="İşlem dayanağı" name="evidence" required minLength={3} placeholder="Kazanımın doğrulandığı kayıt / dayanak"/><Button type="submit" level="secondary">TANI</Button></form></details></>}{["founder","admin"].includes(role)&&<details><summary>Kıdem Nişanı tanı</summary><p>Aktif üyelik ve geçmiş süre yönetim tarafından değerlendirilir. Otomatik atama yapılmaz.</p><form action="/api/badges" method="post"><input type="hidden" name="action" value="recognize"/><input type="hidden" name="badge_id" value={catalog?.find(b=>b.slug==="kidem-nisani"&&b.active)?.id||""}/><MemberPicker name="target_id" label="Aktif üye seç" scope="active"/><Input aria-label="İşlem gerekçesi" name="reason" required minLength={3} maxLength={2000} placeholder="Kıdemin tanınma gerekçesi"/><Textarea aria-label="İşlem dayanağı" name="evidence" required minLength={3} maxLength={2000} placeholder="Değerlendirilen süre ve aktiflik dayanağı"/><Button type="submit" level="secondary" disabled={!catalog?.some(b=>b.slug==="kidem-nisani"&&b.active)}>KIDEMİ TANI</Button></form></details>}
 <details><summary>İşlem geçmişi</summary>{(manager?.history??[]).slice(0,100).map((e:{id:string;badge_id:string;user_id:string;event:string;created_at:string;reason:string;evidence?:string})=><article className="badgeHistoryRow" key={e.id}><b>{catalog?.find(b=>b.id===e.badge_id)?.name} · {members.find(m=>m.id===e.user_id)?.display_name||"Arşiv üyesi"}</b><small>{e.event} · {new Date(e.created_at).toLocaleString("tr-TR")}</small><p>{e.reason}</p>{e.evidence&&<p>Dayanak: {e.evidence}</p>}</article>)}</details></section>;
}
