"use client";
import {Input} from "@/components/ui/Primitives";

import {CodexCompilation} from "@/components/CodexCompilation";
import {NormBadge} from "@/components/NormBadge";
import {useMemo,useState} from "react";
import {RichText} from "@/components/RichText";
import {CodexComposer} from "@/components/CodexComposer";
import {richPlain} from "@/lib/rich-text";
import {type CodexRule,isSecondary,isEffective,canEditRule,codexKindLabel,codexTab} from "@/lib/codex";
type Section={number:string;title:string};
type Revision={id:string;regulation_id:string;revision:number;title:string;body:string;change_reason:string|null;changed_at:string};
const date=(v:string|null)=>v?new Date(v).toLocaleString("tr-TR"):"—";
export function CodexWorkspace({rules,sections,initialRule,initialSection,heroImage,actorRole,actorId,issuers,revisions,action,initialTab,canPublishDecision=false,canCompile=false}:{rules:CodexRule[];sections:Section[];initialRule?:string;initialSection?:string;heroImage:string;initialTab?:string;canPublishDecision?:boolean;canCompile?:boolean;actorRole?:string;actorId?:string;issuers:{id:string;role:string;display_name?:string;handle?:string}[];revisions:Revision[];action:(formData:FormData)=>Promise<void>}){
 const first=rules.find(r=>r.id===initialRule)||rules.find(r=>r.section_number===(initialSection||"01")&&isEffective(r))||rules[0];
 const [tab,setTab]=useState(["primary","directives","decisions"].includes(initialTab||"")?initialTab!:codexTab(first||{kind:null})),[selectedId,setSelectedId]=useState(first?.id||""),[term,setTerm]=useState(""),[openSections,setOpenSections]=useState<Set<string>>(()=>new Set([initialSection||first?.section_number||"01"]));
 const filtered=useMemo(()=>rules.filter(r=>tab===codexTab(r)&&`${r.title} ${r.body||""} ${r.number||""}`.toLocaleLowerCase("tr-TR").includes(term.trim().toLocaleLowerCase("tr-TR"))).sort((a,b)=>tab==="decisions"?(Date.parse(b.published_at||"")||0)-(Date.parse(a.published_at||"")||0)||b.id.localeCompare(a.id):(a.number||"").localeCompare(b.number||"","tr",{numeric:true})),[rules,tab,term]);
 const selected=filtered.find(r=>r.id===selectedId)||(tab==="primary"?filtered[0]:undefined),basis=rules.find(r=>r.id===selected?.basis_rule_id);
 const children=rules.filter(r=>r.basis_rule_id===selected?.id),history=revisions.filter(r=>r.regulation_id===selected?.id);
 const editable=!!selected&&(selected.kind!=="KARAR"||canPublishDecision)&&canEditRule(actorRole,actorId,selected,issuers.find(p=>p.id===selected.created_by)?.role);
 function switchTab(next:string){setTab(next);setSelectedId("");const params=new URLSearchParams();params.set("tab",next);window.history.replaceState(null,"",`/kodeks?${params}`);}
 function choose(rule:CodexRule){setTab(codexTab(rule));setSelectedId(rule.id);setOpenSections(prev=>new Set(prev).add(rule.section_number||"01"));historySync(rule);}
 function historySync(rule:CodexRule){const params=new URLSearchParams();params.set("rule",rule.id);params.set("section",rule.section_number||"01");window.history.replaceState(null,"",`/kodeks?${params}`);}
 const needsReview=!!selected&&selected.kind==="YÖNERGE"&&(!basis||!isEffective(basis)||basis.revision!==selected.basis_revision);
 return <><section className="codexV3Hero unifiedPageHero" style={{backgroundImage:`linear-gradient(90deg,rgba(4,3,2,.82),rgba(4,3,2,.25) 55%,rgba(4,3,2,.12)),url(${heroImage})`}}><div><h1>KODEKS</h1><p>Kurallar, ilkeler, yönergeler ve icra kararları.</p></div></section>
 <nav className="codexTabs" aria-label="Kodeks bölümleri"><button type="button" aria-pressed={tab==="primary"} onClick={()=>switchTab("primary")}>KURALLAR & İLKELER</button><button type="button" aria-pressed={tab==="directives"} onClick={()=>switchTab("directives")}>YÖNERGELER</button><button type="button" aria-pressed={tab==="decisions"} onClick={()=>switchTab("decisions")}>İCRA KARARLARI</button>{actorId&&actorRole&&actorRole!=="guest"&&<a href="/disiplin">DİSİPLİN KARARLARI</a>}</nav>
 <div className="codexTools"><CodexCompilation canCompile={canCompile}/></div>
 <section className="codexV3Bar"><strong>{filtered.length} {tab==="decisions"?"KARAR":tab==="directives"?"YÖNERGE":"HÜKÜM"}</strong><div className="codexV3Controls"><Input aria-label="Hüküm ara" value={term} onChange={e=>setTerm(e.target.value)} placeholder="Hüküm ara…"/></div></section>
 <div className={"codexV3Workspace codexLayout-"+tab+(selected?" hasSelection":"")}><aside className="codexV3Index">{tab!=="primary"?<div className="codexDocumentList">{filtered.length?filtered.map(r=><button type="button" key={r.id} onClick={()=>choose(r)} aria-pressed={selected?.id===r.id} className="codexDocumentRow"><span className="codexDocumentMeta"><b>§ {r.number}</b><NormBadge kind={r.kind}/><small>{r.status==="taslak"?"TASLAK":isEffective(r)?"YÜRÜRLÜKTE":r.status==="yururlukte"?"İLERİ TARİH":"ARŞİV"}</small></span><strong>{r.title}</strong><span className="codexDocumentSummary">{richPlain(r.body||"").slice(0,160)}</span><span className="codexDocumentMeta"><time>{date(r.published_at)}</time>{issuers.find(p=>p.id===r.created_by)?.display_name&&<small>{issuers.find(p=>p.id===r.created_by)?.display_name}</small>}{r.basis_rule_id&&<small>DAYANAK § {rules.find(b=>b.id===r.basis_rule_id)?.number||"—"}</small>}</span></button>):<p className="notice">Bu görünümde kayıt bulunmuyor.</p>}</div>:sections.map(sec=>{const items=filtered.filter(r=>r.section_number===sec.number),open=openSections.has(sec.number);return <section key={sec.number} className={open?"open":""}><button type="button" className="codexV3Section" aria-expanded={open} onClick={()=>setOpenSections(prev=>{const next=new Set(prev);if(next.has(sec.number))next.delete(sec.number);else next.add(sec.number);return next;})}><b>§ {sec.number}</b><span>{sec.title}</span><em>{items.length}</em><i>{open?"⌃":"⌄"}</i></button>{open&&<div className="codexV3Items">{items.map(r=><button type="button" key={r.id} onClick={()=>choose(r)} className={selected?.id===r.id?"selected":""}><b>§ {r.number}</b><span><strong>{r.title}</strong><NormBadge kind={r.kind}/></span>{!isEffective(r)&&<em>{r.status==="taslak"?"TASLAK":r.status==="yururlukte"?"İLERİ TARİH":"ARŞİV"}</em>}</button>)}</div>}</section>;})}</aside>
 <section className="codexV3Reader">{tab!=="primary"&&selected&&<button className="qgAction codexBack" type="button" onClick={()=>{setSelectedId("");const params=new URLSearchParams();params.set("tab",tab);window.history.replaceState(null,"",`/kodeks?${params}`);}}>← Listeye dön</button>}{selected?<article className="codexV3Paper"><header><span>§ {selected.number}</span><h2>{selected.title}</h2><div><NormBadge kind={selected.kind}/><i>•</i><b>{selected.legacy_announcement_id?"TARİHSEL KAYIT":selected.status==="taslak"?"TASLAK":isEffective(selected)?"● YÜRÜRLÜKTE":selected.status==="yururlukte"?"İLERİ TARİHLİ":"ARŞİV"}</b><i>•</i><b>SÜRÜM {selected.revision}</b></div>{selected.kind==="KARAR"&&<p>Yayımlanan icra kararları duyurularda otomatik görünür. <a href="/duyurular?category=karar" className="qgAction">Duyurularda görüntüle</a></p>}{isSecondary(selected)&&(basis||!selected.legacy_announcement_id)&&<p>{basis?<button className="codexBasisLink" type="button" onClick={()=>choose(basis)}>DAYANAK § {basis.number} — {basis.title}</button>:"DAYANAK EKSİK"}</p>}</header>
 {needsReview&&<p className="notice">Dayanak kural değişti veya yürürlükten kalktı. Yönerge yeniden incelenmeli; incelenene kadar disiplin dayanağı olarak seçilemez.</p>}
 <div className="codexV3Body"><RichText value={selected.body||"Metin girilmemiş."}/></div><footer><div><span>YÜRÜRLÜK<strong>{date(selected.effective_at)}</strong></span></div><div><span>SON DEĞİŞİKLİK<strong>{date(selected.updated_at)}</strong></span></div></footer>
 {children.length>0&&<section className="codexRelations"><h3>Bu kurala dayanan düzenlemeler</h3>{children.map(r=><button key={r.id} type="button" onClick={()=>choose(r)}>{codexKindLabel(r.kind)} § {r.number} — {r.title}{r.basis_revision!==selected.revision?" · İNCELEME GEREKİYOR":""}</button>)}</section>}
 {editable&&<CodexComposer key={selected.id+":"+selected.revision} action={action} sections={sections} rules={rules} founder={actorRole==="founder"} rule={selected} canPublishDecision={canPublishDecision}/>}
 {history.length>0&&<section className="codexHistory"><h3>Değişiklik geçmişi</h3>{history.map(r=><details key={r.id}><summary>Sürüm {r.revision} · {date(r.changed_at)} · {r.change_reason||"Değişiklik"}</summary><h4>{r.title}</h4><RichText value={r.body}/></details>)}</section>}
 </article>:<article className="codexV3Paper codexV3Empty"><h2>{tab==="primary"?"KURALLAR & İLKELER":tab==="directives"?"YÖNERGELER":"İCRA KARARLARI"}</h2><p>{filtered.length?"Okumak için listeden bir belge seçin.":"Bu görünümde hüküm bulunmuyor."}</p></article>}</section></div>
 {["founder","admin","moderator"].includes(actorRole||"")&&(tab!=="decisions"||canPublishDecision)&&<CodexComposer action={action} sections={sections} rules={rules} founder={actorRole==="founder"} canPublishDecision={canPublishDecision} initialKind={tab==="decisions"?"KARAR":tab==="directives"?"YÖNERGE":undefined} key={tab}/>}</>;
}
