"use client";
import {RichText} from "@/components/RichText";
import {useState} from "react";
import {RichTextEditor} from "@/components/RichTextEditor";
import {type CodexRule,isEffective,codexKindLabel} from "@/lib/codex";
export function CodexComposer({action,sections,rules,founder=false,rule,initialKind,canPublishDecision=false}:{action:(formData:FormData)=>void|Promise<void>;sections:{number:string;title:string}[];rules:CodexRule[];founder?:boolean;initialKind?:string;canPublishDecision?:boolean;rule?:CodexRule & {application_scope?:string|null}}){
 const [open,setOpen]=useState(false),[kind,setKind]=useState(rule?.kind||initialKind||(founder?"KURAL":"YÖNERGE"));
 const [basisId,setBasisId]=useState(rule?.basis_rule_id||"");
 const basis=rules.find(r=>r.id===basisId);
 const secondary=kind==="YÖNERGE"||kind==="KARAR";
 return <><button type="button" className="codexComposerLaunch" onClick={()=>setOpen(true)}>{rule?"HÜKMÜ DÜZENLE":"＋ YENİ HÜKÜM YAYIMLA"}</button>{open&&<div className="codexComposerOverlay" role="dialog" aria-modal="true" aria-label={rule?"Hükmü düzenle":"Yeni hüküm yayımla"} onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><section className="codexComposerDrawer"><header><div><span>{rule?"DEĞİŞİKLİK":"YENİ KAYIT"}</span><h2>{rule?"Hükmü Düzenle":"Hüküm Yayımla"}</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Kapat">×</button></header><form action={action} className="codexComposerForm">
 {rule&&<><input type="hidden" name="id" value={rule.id}/><input type="hidden" name="revision" value={rule.revision||1}/></>}
 <div className="codexComposerMeta"><label><span>BÖLÜM</span><select name="section_number" defaultValue={rule?.section_number||"01"} required>{sections.map(s=><option key={s.number} value={s.number}>§ {s.number} — {s.title}</option>)}</select></label><label><span>HÜKÜM NO</span><input name="number" required defaultValue={rule?.number||""} placeholder="Kural: 03.04 · Yönerge: 03.04/1"/></label><label><span>TÜR</span>{rule?<><input type="hidden" name="kind" value={kind}/><b>{codexKindLabel(kind)}</b></>:<select name="kind" value={kind||"KURAL"} onChange={e=>setKind(e.target.value)}>{founder&&<><option>KURAL</option><option>İLKE</option></>}<option>YÖNERGE</option>{canPublishDecision&&<option value="KARAR">İCRA KARARI</option>}</select>}</label><label className="codexTitleField"><span>BAŞLIK</span><input name="title" required defaultValue={rule?.title||""}/></label></div>
 {secondary&&<label>DAYANAK HÜKÜM<select name="basis_rule_id" required value={basisId} onChange={e=>setBasisId(e.target.value)}><option value="" disabled>Kural seç</option>{rules.filter(r=>(r.kind==="KURAL"||(kind==="KARAR"&&r.kind==="YÖNERGE"&&rules.some(p=>p.id===r.basis_rule_id&&isEffective(p)&&p.revision===r.basis_revision)))&&(isEffective(r)||r.id===rule?.basis_rule_id)).map(r=><option key={r.id} value={r.id}>§ {r.number} — {r.title} (sürüm {r.revision})</option>)}</select></label>}
 {secondary&&basis&&<details className="codexBasisPreview" open><summary>Dayanak hüküm · sürüm {basis.revision}</summary><RichText value={basis.body||""}/><input type="hidden" name="basis_revision" value={basis.revision||1}/></details>}
 {secondary&&<label>UYGULAMA / GÖREV ALANI<input name="application_scope" required maxLength={500} defaultValue={rule?.application_scope||""} placeholder="İşlemin uygulanacağı görev ve yönetim alanı"/></label>}
 {kind==="KARAR"&&<><label>DUYURU ÖNEMİ<select name="decision_priority" defaultValue={rule?.decision_priority||"normal"}><option value="normal">Normal</option><option value="important">Önemli</option><option value="critical">Kritik</option></select></label><label><span><input name="decision_pinned" type="checkbox" defaultChecked={rule?.decision_pinned}/> Duyurularda sabitle</span></label><p className="notice">Yayımlanan icra kararı otomatik duyurulur. İleri tarihli yürürlük ayrıca gösterilir; taslak duyurulmaz.</p></>}
 <div className="codexComposerGrid"><section className="codexWriting"><RichTextEditor name="body" defaultValue={rule?.body||""} required rows={16}/></section><aside className="codexSealPanel"><header><b>YAYIM / MÜHÜRLEME</b><span>Resmî kayıt</span></header>
 <label><span>YÜRÜRLÜK</span><select name="effective_mode" defaultValue={rule?"keep":"now"}>{rule&&<option value="keep">Mevcut yürürlük tarihini koru</option>}<option value="now">Derhal</option>{!rule&&<option value="scheduled">İleri tarih</option>}</select></label><label><span>İLERİ YÜRÜRLÜK TARİHİ</span><input type="datetime-local" name="effective_at"/></label>
 <label>DURUM<select name="status" defaultValue={rule?.status||"yururlukte"}><option value="yururlukte">Yayımla / yürürlükte</option>{(!rule||rule.status==="taslak")&&<option value="taslak">Taslak — yayımlanmaz</option>}<option value="yururlukten_kaldirildi">Yürürlükten kaldırıldı</option></select></label>
 <label><span>DEĞİŞİKLİK / YAYIM GEREKÇESİ</span><textarea name="reason" required rows={4}/></label><div className="codexSealNotice">Dayanak kural güncellendiğinde yönergeyi yeniden inceleyip kaydet. Değişiklik tarihi ve önceki sürüm otomatik kaydedilir.</div><button className="codexSealButton" type="submit">{rule?"DEĞİŞİKLİĞİ KAYDET":"KODEKS'E MÜHÜRLE"} →</button></aside></div></form></section></div>}</>;
}
