"use client";
import {Dialog} from "@/components/ui/Dialog";
import {IconButton,Select,Input,Textarea} from "@/components/ui/Primitives";
import {RichText} from "@/components/RichText";
import {useState} from "react";
import {RichTextEditor} from "@/components/RichTextEditor";
import {type CodexRule,isEffective,codexKindLabel} from "@/lib/codex";
export function CodexComposer({action,sections,rules,founder=false,rule,initialKind,canPublishDecision=false}:{action:(formData:FormData)=>void|Promise<void>;sections:{number:string;title:string}[];rules:CodexRule[];founder?:boolean;initialKind?:string;canPublishDecision?:boolean;rule?:CodexRule & {application_scope?:string|null}}){
 const [open,setOpen]=useState(false),[kind,setKind]=useState(rule?.kind||initialKind||(founder?"KURAL":"YÖNERGE"));
 const [section,setSection]=useState(rule?.section_number||"01");
 const [structure,setStructure]=useState("independent");
 const [basisId,setBasisId]=useState(rule?.basis_rule_id||"");
 const basis=rules.find(r=>r.id===basisId);
 const secondary=kind==="YÖNERGE"||kind==="KARAR";
 return <><button type="button" className="codexComposerLaunch" onClick={()=>setOpen(true)}>{rule?"HÜKMÜ DÜZENLE":"＋ YENİ HÜKÜM YAYIMLA"}</button>{open&&<Dialog open onClose={()=>setOpen(false)} title={rule?"Hükmü düzenle":"Yeni hüküm yayımla"} className="codexComposerOverlay"><section className="codexComposerDrawer"><header><div><span>{rule?"DEĞİŞİKLİK":"YENİ KAYIT"}</span><h2>{rule?`§ ${rule.number} — Hükmü Düzenle`:"Hüküm Yayımla"}</h2></div><IconButton icon="close" label="Kapat" onClick={()=>setOpen(false)}/></header><form action={action} className="codexComposerForm">
 {rule&&<><input type="hidden" name="id" value={rule.id}/><input type="hidden" name="revision" value={rule.revision||1}/></>}
 <div className="codexComposerMeta"><label><span>BÖLÜM</span><Select name="section_number" value={section} onChange={e=>setSection(e.target.value)} required>{sections.map(s=><option key={s.number} value={s.number}>§ {s.number} — {s.title}</option>)}</Select></label>{rule&&<input type="hidden" name="number" value={rule.number||""}/>}<label><span>TÜR</span>{rule?<><input type="hidden" name="kind" value={kind}/><b>{codexKindLabel(kind)}</b></>:<Select name="kind" value={kind||"KURAL"} onChange={e=>setKind(e.target.value)}>{founder&&<><option>KURAL</option><option>İLKE</option></>}<option>YÖNERGE</option>{canPublishDecision&&<option value="KARAR">İCRA KARARI</option>}</Select>}</label><label className="codexTitleField"><span>BAŞLIK</span><Input name="title" required defaultValue={rule?.title||""}/></label></div>
 {!rule&&!secondary&&<><label>HÜKÜM YAPISI<Select value={structure} onChange={e=>setStructure(e.target.value)}><option value="independent">Bağımsız hüküm</option><option value="child">Mevcut hükme alt hüküm ekle</option></Select></label>{structure==="child"&&<label>ÜST HÜKÜM<Select name="parent_rule_id" required><option value="">Üst hüküm seç</option>{rules.filter(r=>["KURAL","İLKE"].includes(r.kind||"")&&r.section_number===section).map(r=><option key={r.id} value={r.id}>§ {r.number} — {r.title}</option>)}</Select></label>}</>}
 {secondary&&<label>DAYANAK HÜKÜM<Select name="basis_rule_id" required value={basisId} onChange={e=>setBasisId(e.target.value)}><option value="" disabled>Kural seç</option>{rules.filter(r=>(r.kind==="KURAL"||(kind==="KARAR"&&r.kind==="YÖNERGE"&&rules.some(p=>p.id===r.basis_rule_id&&isEffective(p)&&p.revision===r.basis_revision)))&&(isEffective(r)||r.id===rule?.basis_rule_id)).map(r=><option key={r.id} value={r.id}>§ {r.number} — {r.title} (sürüm {r.revision})</option>)}</Select></label>}
 {secondary&&basis&&<details className="codexBasisPreview" open><summary>Dayanak hüküm · sürüm {basis.revision}</summary><RichText value={basis.body||""}/><input type="hidden" name="basis_revision" value={basis.revision||1}/></details>}
 {secondary&&<label>UYGULAMA KAPSAMI<Input name="application_scope" maxLength={500} defaultValue={rule?.application_scope||""} placeholder="Gerekiyorsa kapsamı belirt; Kaptan işlemlerinde zorunludur"/></label>}
 {kind==="KARAR"&&<><label>DUYURU ÖNEMİ<Select name="decision_priority" defaultValue={rule?.decision_priority||"normal"}><option value="normal">Normal</option><option value="important">Önemli</option><option value="critical">Kritik</option></Select></label><label><span><input name="decision_pinned" type="checkbox" defaultChecked={rule?.decision_pinned}/> Duyurularda sabitle</span></label><p className="notice">Yayımlanan icra kararı otomatik duyurulur. İleri tarihli yürürlük ayrıca gösterilir; taslak duyurulmaz.</p></>}
 <div className="codexComposerGrid"><section className="codexWriting"><RichTextEditor name="body" defaultValue={rule?.body||""} required rows={16}/></section><aside className="codexSealPanel"><header><b>YAYIM / MÜHÜRLEME</b><span>Resmî kayıt</span></header>
 <label><span>YÜRÜRLÜK</span><Select name="effective_mode" defaultValue={rule?"keep":"now"}>{rule&&<option value="keep">Mevcut yürürlük tarihini koru</option>}<option value="now">Derhal</option>{!rule&&<option value="scheduled">İleri tarih</option>}</Select></label><label><span>İLERİ YÜRÜRLÜK TARİHİ</span><Input type="datetime-local" name="effective_at"/></label>
 <label>DURUM<Select name="status" defaultValue={rule?.status||"yururlukte"}><option value="yururlukte">Yayımla / yürürlükte</option>{(!rule||rule.status==="taslak")&&<option value="taslak">Taslak — yayımlanmaz</option>}<option value="yururlukten_kaldirildi">Yürürlükten kaldırıldı</option></Select></label>
 <label><span>DEĞİŞİKLİK / YAYIM GEREKÇESİ</span><Textarea name="reason" required rows={4}/></label><div className="codexSealNotice">Dayanak kural güncellendiğinde yönergeyi yeniden inceleyip kaydet. Değişiklik tarihi ve önceki sürüm otomatik kaydedilir.</div><button className="codexSealButton" type="submit">{rule?"DEĞİŞİKLİĞİ KAYDET":"KODEKS'E MÜHÜRLE"} →</button></aside></div></form></section></Dialog>}</>;
}
