"use client";
import {Input} from "@/components/ui/Primitives";

import {useState} from "react";
export function CodexCompilation({canCompile}:{canCompile:boolean}){
 const [open,setOpen]=useState(false),[confirmation,setConfirmation]=useState(""),[decisions,setDecisions]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[url,setUrl]=useState("");
 async function request(create:boolean){setBusy(true);setMessage("");setUrl("");try{let response:Response;if(create){const f=new FormData();f.set("confirmation",confirmation);f.set("decisions",String(decisions));response=await fetch("/api/codex/compilations",{method:"POST",body:f});}else response=await fetch("/api/codex/compilations?decisions="+decisions);const data=await response.json();if(!response.ok)throw new Error(data.error||"İşlem tamamlanamadı.");setUrl(data.url);setMessage(data.current===false?"Bu bir arşiv nüshasıdır. Kodeks bu derlemeden sonra değişmiş.":"Derlenmiş metin hazır.");}catch(e){setMessage(e instanceof Error?e.message:"İşlem tamamlanamadı.");}finally{setBusy(false)}}
 return <><button className="qgAction" aria-expanded={open} onClick={()=>setOpen(!open)}>PDF çıktısı al ↓</button>{open&&<section className="codexCompilation"><h2>Kodeksi Derle</h2><p>Yürürlükteki kurallar, ilkeler ve yönergeler. Kişisel disiplin kayıtları dahil edilmez.</p><label><input type="checkbox" disabled={busy} checked={decisions} onChange={e=>{setDecisions(e.target.checked);setUrl("");setMessage("")}}/> İcra kararlarını ayrı ek olarak dahil et</label><button disabled={busy} onClick={()=>request(false)}>MEVCUT DERLEMEYİ AÇ</button>{canCompile&&<><label>Yeni derleme için KODEKSİ DERLE yaz<Input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label><button disabled={busy||confirmation!=="KODEKSİ DERLE"} onClick={()=>request(true)}>{busy?"HAZIRLANIYOR…":"PDF’Yİ OLUŞTUR"}</button></>}{message&&<p role="status">{message}</p>}{url&&<a href={url} target="_blank" rel="noreferrer" className="qgAction">PDF’Yİ GÖRÜNTÜLE / İNDİR</a>}</section>}</>;
}
