"use client";
import {useEffect,useRef,useState,useTransition} from "react";
import type {DesignSettings} from "@/lib/design";
import {resetDesign,restoreDesign,saveDesign} from "@/app/control/design/actions";
import {createClient} from "@/lib/supabase/client";
const Range=({label,value,min,max,onChange}:{label:string,value:number,min:number,max:number,onChange:(n:number)=>void})=><label className="designField"><span>{label}<b>{value}</b></span><input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
const targets=[["emblemSrc","Ana arma"],["commandBackground","Karargâh arka plan"],["quadSrc","Quad"],["loginBackground","Login arka plan"],["roomCodex","Kurallar"],["roomRegistry","Topluluk"],["roomDecrees","Duyurular"],["roomTribunal","Cezalar"],["roomTreasury","Bütçe"]] as const;
export function DesignEditor({initial,history}:{initial:DesignSettings,history:{id:number,created_at:string}[]}){
 const [d,setD]=useState(initial),[pending,start]=useTransition(),[saved,setSaved]=useState(false),[uploading,setUploading]=useState(""),frame=useRef<HTMLIFrameElement>(null);
 const set=(k:keyof DesignSettings,v:any)=>{setSaved(false);setD(x=>({...x,[k]:v}))};
 useEffect(()=>{frame.current?.contentWindow?.postMessage({type:"qgang-design-preview",design:d},location.origin)},[d]);
 const upload=async(k:keyof DesignSettings,file?:File)=>{if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>10*1024*1024){alert("PNG, JPG veya WebP; en fazla 10 MB.");return}setUploading(String(k));const s=createClient(),ext=file.name.split(".").pop()?.toLowerCase()||"webp",name=`${String(k)}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await s.storage.from("qgang-design").upload(name,file,{cacheControl:"3600"});if(error){alert(error.message);setUploading("");return}const {data}=s.storage.from("qgang-design").getPublicUrl(name);set(k,data.publicUrl);setUploading("")};
 return <div className="designCenter">
  <aside className="designControls">
   <div className="designHead"><span>TASARIM MERKEZİ V2</span><h1>Q-GANG görünümü</h1><p>Değiştir, canlı gör, sonra yayınla.</p></div>
   <details open><summary>Marka & Sidebar</summary><div className="colorRow">{(["primary","bone","bronze"] as const).map(k=><label key={k}>{k==="primary"?"Kırmızı":k==="bone"?"Kemik":"Bronz"}<input type="color" value={d[k]} onChange={e=>set(k,e.target.value)}/></label>)}</div><Range label="Sidebar genişliği" value={d.sidebarWidth} min={160} max={260} onChange={v=>set("sidebarWidth",v)}/><Range label="Arma boyutu" value={d.sidebarEmblem} min={36} max={100} onChange={v=>set("sidebarEmblem",v)}/></details>
   <details open><summary>Karargâh & Konsey</summary><Range label="Quad ölçeği %" value={d.quadScale} min={65} max={140} onChange={v=>set("quadScale",v)}/><Range label="Quad Y %" value={d.quadY} min={-30} max={30} onChange={v=>set("quadY",v)}/><Range label="Karartma" value={d.heroOverlay} min={0} max={80} onChange={v=>set("heroOverlay",v)}/>
    <div className="councilEditor"><span className="designSubhead">KONSEY ÜYELERİ</span>{d.council.map((m,i)=><div className="councilSlot" key={m.id}><label className="councilToggle"><input type="checkbox" checked={m.enabled} onChange={e=>set("council",d.council.map((x,j)=>j===i?{...x,enabled:e.target.checked}:x))}/><b>{m.id.replace("-"," ").toUpperCase()}</b><em>{m.enabled?"Aktif":"Gizli"}</em></label>{m.enabled&&<><Range label="Ölçek %" value={m.scale} min={50} max={160} onChange={v=>set("council",d.council.map((x,j)=>j===i?{...x,scale:v}:x))}/><Range label="X %" value={m.x} min={-30} max={30} onChange={v=>set("council",d.council.map((x,j)=>j===i?{...x,x:v}:x))}/><Range label="Y %" value={m.y} min={-30} max={30} onChange={v=>set("council",d.council.map((x,j)=>j===i?{...x,y:v}:x))}/><label className="assetUpload">Görsel<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;setUploading(m.id);const s=createClient(),ext=file.name.split(".").pop()||"webp",name=`council/${m.id}-${Date.now()}.${ext}`;s.storage.from("qgang-design").upload(name,file).then(({error})=>{if(error)alert(error.message);else{const {data}=s.storage.from("qgang-design").getPublicUrl(name);set("council",d.council.map((x,j)=>j===i?{...x,src:data.publicUrl}:x))}setUploading("")})}}/>{uploading===m.id?"Yükleniyor…":"Değiştir"}</label></>}</div>)}</div>
   </details>
   <details><summary>Login</summary><Range label="Panel genişliği" value={d.loginPanelWidth} min={360} max={720} onChange={v=>set("loginPanelWidth",v)}/><Range label="Arma boyutu" value={d.loginEmblem} min={48} max={160} onChange={v=>set("loginEmblem",v)}/><Range label="Karartma" value={d.loginOverlay} min={0} max={80} onChange={v=>set("loginOverlay",v)}/></details>
   <details><summary>Görsel Kütüphanesi</summary><div className="assetGrid">{targets.map(([k,label])=><div className="assetRow" key={k}><div><b>{label}</b><small>{String(d[k]).split("/").pop()}</small></div><label className="assetUpload"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(k,e.target.files?.[0])}/>{uploading===k?"Yükleniyor…":"Görsel yükle"}</label></div>)}</div></details>
   <details open><summary>Site Kimliği & Sekme</summary><label className="designText">Site başlığı<input value={d.siteTitle} onChange={e=>set("siteTitle",e.target.value)}/></label><label className="designText">Genel açıklama<textarea rows={2} value={d.siteDescription} onChange={e=>set("siteDescription",e.target.value)}/></label><div className="assetRow"><div><b>Sekme faviconu</b><small>{d.favicon.split("/").pop()}</small></div><label className="assetUpload"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload("favicon",e.target.files?.[0])}/>{uploading==="favicon"?"Yükleniyor…":"Favicon yükle"}</label></div><span className="designSubhead">SAYFA AÇIKLAMALARI</span>{([["home","Ana sayfa"],["rules","Kurallar"],["members","Topluluk"],["announcements","Duyurular"],["discipline","Disiplin"],["budget","Bütçe"]] as const).map(([k,label])=><label className="designText" key={k}>{label}<textarea rows={2} value={d.pageDescriptions[k]||""} onChange={e=>set("pageDescriptions",{...d.pageDescriptions,[k]:e.target.value.slice(0,180)})}/></label>)}</details>\n   <details><summary>Metin</summary><label className="designText">Motto<input value={d.motto} onChange={e=>set("motto",e.target.value)}/></label><label className="designText">Sağ şerit<textarea rows={3} value={d.systemLine} onChange={e=>set("systemLine",e.target.value)}/></label></details>
   <details><summary>Geçmiş & Geri Al</summary><div className="designHistory">{history.length?history.map(h=><button key={h.id} onClick={()=>start(async()=>setD(await restoreDesign(h.id)))}><b>{new Date(h.created_at).toLocaleString("tr-TR")}</b><span>Bu sürüme dön ↶</span></button>):<p>Henüz önceki yayın yok.</p>}</div></details>
   <div className="designActions"><button onClick={()=>start(async()=>{setD(await resetDesign());setSaved(false)})}>Varsayılana dön</button><button className="primary" disabled={pending||!!uploading} onClick={()=>start(async()=>{setD(await saveDesign(d));setSaved(true)})}>{pending?"Kaydediliyor…":saved?"Yayınlandı ✓":"Yayınla"}</button></div>
  </aside>
  <section className="designPreview"><header><span>GERÇEK SAYFA · CANLI ÖNİZLEME</span><a href="/" target="_blank">Yeni sekmede aç ↗</a></header><iframe ref={frame} src="/?designPreview=1" title="Q-GANG canlı tasarım önizlemesi" onLoad={()=>frame.current?.contentWindow?.postMessage({type:"qgang-design-preview",design:d},location.origin)}/><p>Değişiklikler yalnızca bu önizlemede görünür. “Yayınla” gerçek siteye uygular.</p></section>
 </div>
}