"use client";
import {Input} from "@/components/ui/Primitives";

import {useEffect,useRef,useState,useTransition} from "react";
import type {DesignSettings} from "@/lib/design";
import {resetDesign,restoreDesign,saveDesign} from "@/app/control/design/actions";
import {createClient} from "@/lib/supabase/client";
const Range=({label,value,min,max,onChange}:{label:string,value:number,min:number,max:number,onChange:(n:number)=>void})=><label className="designField"><span>{label}<b>{value}</b></span><input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
const targets=[["emblemSrc","Ana arma"],["commandBackground","Karargâh arka plan"],["quadSrc","Quad"],["loginBackground","Login arka plan"],["roomCodex","Kurallar"],["roomRegistry","Topluluk"],["roomDecrees","Duyurular"],["roomTribunal","Cezalar"],["roomTreasury","Bütçe"]] as const;
export function DesignEditor({initial,history}:{initial:DesignSettings,history:{id:number,created_at:string}[]}){
 const [d,setD]=useState(initial),[pending,start]=useTransition(),[saved,setSaved]=useState(false),[uploading,setUploading]=useState(""),frame=useRef<HTMLIFrameElement>(null);
 const set=(k:keyof DesignSettings,v:any)=>{setSaved(false);setD(x=>({...x,[k]:v}))};
 useEffect(()=>{frame.current?.contentWindow?.postMessage({type:"qgang-design-preview",design:d},location.origin)},[d]);
 const upload=async(k:keyof DesignSettings,file?:File)=>{if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>10*1024*1024){alert("PNG, JPG veya WebP; en fazla 10 MB.");return}setUploading(String(k));const s=createClient(),ext=file.name.split(".").pop()?.toLowerCase()||"webp",name=`${String(k)}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await s.storage.from("qgang-design").upload(name,file,{cacheControl:"3600"});if(error){alert(error.message);setUploading("");return}const {data}=s.storage.from("qgang-design").getPublicUrl(name);set(k,data.publicUrl);setUploading("")};
 return <div className="designCenter">
  <aside className="designControls">
   <div className="designHead"><span>TASARIM MERKEZİ 3.0</span><h1>Görünüm</h1><p>Gerçekten kullanılan görselleri ve ana sahneyi yönet.</p></div>
   <details open><summary>Karargâh & Konsey</summary><Range label="Quad ölçeği %" value={d.quadScale} min={65} max={140} onChange={v=>set("quadScale",v)}/><Range label="Quad Y %" value={d.quadY} min={-30} max={30} onChange={v=>set("quadY",v)}/><Range label="Karartma" value={d.heroOverlay} min={0} max={80} onChange={v=>set("heroOverlay",v)}/>
    <div className="councilEditor"><span className="designSubhead">KONSEY PORTRELERİ</span><button type="button" className="qgAction" onClick={()=>set("council",[...d.council,{id:`portrait-${crypto.randomUUID()}`,enabled:true,scale:100,x:0,y:0,src:"/brand/command/council-left-1.webp"}])}>+ Portre ekle</button><p className="councilPosterHint">Aktif üyeler Quad\’ın arkasına otomatik ve dengeli yerleşir. Yalnız portre ölçeğini ayarla.</p>{d.council.map((m,i)=><div className="councilSlot" key={m.id}><label className="councilToggle"><input type="checkbox" checked={m.enabled} onChange={e=>set("council",d.council.map((x,j)=>j===i?{...x,enabled:e.target.checked}:x))}/><b>{`PORTRE ${i+1}`}</b><em>{m.enabled?"Aktif":"Gizli"}</em></label><button type="button" className="qgAction" disabled={uploading===m.id} aria-label={`Portre ${i+1} kaldır`} onClick={()=>set("council",d.council.filter(x=>x.id!==m.id))}>Kaldır</button>{m.enabled&&<><Range label="Ölçek %" value={m.scale} min={50} max={160} onChange={v=>set("council",d.council.map((x,j)=>j===i?{...x,scale:v}:x))}/><label className="assetUpload">Görsel<Input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>10*1024*1024||!["image/png","image/jpeg","image/webp"].includes(file.type)){alert("PNG, JPG veya WebP; en fazla 10 MB.");return}setUploading(m.id);const s=createClient(),ext=file.name.split(".").pop()||"webp",name=`council/${m.id}-${Date.now()}.${ext}`;s.storage.from("qgang-design").upload(name,file).then(({error})=>{if(error)alert(error.message);else{const {data}=s.storage.from("qgang-design").getPublicUrl(name);setSaved(false);setD(current=>({...current,council:current.council.map(x=>x.id===m.id?{...x,src:data.publicUrl}:x)}))}setUploading("")})}}/>{uploading===m.id?"Yükleniyor…":"Değiştir"}</label></>}</div>)}</div>
   </details>
   <details><summary>Görsel Kütüphanesi</summary><div className="assetGrid">{targets.map(([k,label])=><div className="assetRow" key={k}><div><b>{label}</b><small>{String(d[k]).split("/").pop()}</small></div><label className="assetUpload"><Input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(k,e.target.files?.[0])}/>{uploading===k?"Yükleniyor…":"Görsel yükle"}</label></div>)}</div></details>
   <details><summary>Geçmiş & Geri Al</summary><div className="designHistory">{history.length?history.map(h=><button key={h.id} onClick={()=>start(async()=>setD(await restoreDesign(h.id)))}><b>{new Date(h.created_at).toLocaleString("tr-TR")}</b><span>Bu sürüme dön ↶</span></button>):<p>Henüz önceki yayın yok.</p>}</div></details>
   <div className="designActions"><button onClick={()=>start(async()=>{setD(await resetDesign());setSaved(false)})}>Varsayılana dön</button><button className="primary" disabled={pending||!!uploading} onClick={()=>start(async()=>{setD(await saveDesign(d));setSaved(true)})}>{pending?"Kaydediliyor…":saved?"Yayınlandı ✓":"Yayınla"}</button></div>
  </aside>
  <section className="designPreview"><header><span>GERÇEK SAYFA · CANLI ÖNİZLEME</span><a href="/" target="_blank" className="qgAction">Yeni sekmede aç</a></header><iframe ref={frame} src="/?designPreview=1" title="Q-GANG canlı tasarım önizlemesi" onLoad={()=>frame.current?.contentWindow?.postMessage({type:"qgang-design-preview",design:d},location.origin)}/><p>Değişiklikler yalnızca bu önizlemede görünür. “Yayınla” gerçek siteye uygular.</p></section>
 </div>
}