import {Input,Select,Button} from "@/components/ui/Primitives";
import {createClient} from "@/lib/supabase/server";
import {MemberPicker} from "@/components/MemberPicker";
import {RichTextEditor} from "@/components/RichTextEditor";
import {RichText} from "@/components/RichText";
const labels:Record<string,string>={open:"ALINDI",reviewing:"İNCELENİYOR",resolved:"SONUÇLANDI",dismissed:"KAPATILDI",accepted:"KABUL EDİLDİ",rejected:"REDDEDİLDİ"};
export async function DisciplineRequests({userId,tab="report",target,reported,error,appealed,embedded=false}:{embedded?:boolean;userId:string;tab?:string;target?:string;reported?:string;error?:string;appealed?:string}){
 const s=await createClient();const active=["report","requests","appeal"].includes(tab)?tab:"report";
 const [{data:reports,error:reportError},{data:appeals,error:appealError},{data:actions,error:actionError},{data:member}]=await Promise.all([
 s.from("reports").select("id,reason,status,created_at,reported_user_id").eq("reporter_id",userId).order("created_at",{ascending:false}).limit(100),
 s.from("moderation_appeals").select("id,action_id,body,status,created_at,review_note").eq("user_id",userId).order("created_at",{ascending:false}).limit(100),
 s.from("moderation_actions").select("id,action,reason,created_at,issuer_role,finality_status,status").eq("target_user_id",userId).order("created_at",{ascending:false}).limit(100),
 target&&/^[0-9a-f-]{36}$/i.test(target)&&target!==userId?s.from("profiles").select("id,display_name,handle,role,avatar_url").eq("id",target).maybeSingle():Promise.resolve({data:null})]);
 const eligible=(actions??[]).filter(a=>a.issuer_role!=="founder"&&a.finality_status==="final"&&a.status!=="revoked"&&!(appeals??[]).some(b=>b.action_id===a.id));
 return <section id="discipline-requests" className={"disciplineRequests"+(embedded?" disciplineRequestsEmbedded":"")}><header><small>TOPLULUK GÜVENLİĞİ</small>{embedded?<h2>Şikâyet &amp; İtiraz Başvuruları</h2>:<h1>Disiplin başvuruları</h1>}<p>Üye şikâyeti oluştur, kendi başvurularını takip et veya hakkındaki karara itiraz et.</p></header>{error&&<p className="notice" role="alert">Başvuru gönderilemedi. Bilgilerini kontrol edip yeniden dene.</p>}{(reported||appealed)&&<p className="notice" role="status">Başvurun alındı. Başvurularım bölümünden takip edebilirsin.</p>}{(reportError||appealError||actionError)&&<p className="notice" role="alert">Başvuru bilgileri yüklenemedi. Yeniden dene.</p>}
 {(embedded||active==="report")&&<details open={!!target||(!embedded&&active==="report")}><summary>Yeni şikâyet / bildirim</summary><form className="disciplineRequestForm" action="/api/moderation/report" method="post"><Input type="hidden" name="return_to" value="/disiplin?tab=requests#discipline-requests"/><MemberPicker name="target_id" scope="report" label="Şikâyet edilen üye / hesap" initialMember={member}/><div className="qgEditorField"><span>Şikâyet gerekçesi</span><RichTextEditor label="Şikâyet gerekçesi" name="reason" minLength={5} maxLength={500} required placeholder="Olayı ve şikâyet gerekçeni açıkla…"/></div><p className="muted">Başvurun yetkili yönetim tarafından incelenir; ilgili üyenin profilinde yayımlanmaz.</p><Button level="primary" type="submit" className="qgAction">ŞİKÂYET GÖNDER</Button></form></details>}
 {(embedded||active==="requests")&&<details open={!!reported||!!appealed||active==="requests"}><summary>Başvurularım</summary><div className="disciplineOwnRequests"><h2>Şikâyetlerim</h2>{!reports?.length&&<p>Henüz şikâyet başvurun yok.</p>}{(reports??[]).map(r=><article key={r.id}><header><b>{labels[r.status]||r.status}</b><time>{new Date(r.created_at).toLocaleDateString("tr-TR")}</time></header><RichText value={r.reason}/></article>)}<h2>İtirazlarım</h2>{!appeals?.length&&<p>Henüz itiraz başvurun yok.</p>}{(appeals??[]).map(a=><article key={a.id}><header><b>{labels[a.status]||a.status}</b><time>{new Date(a.created_at).toLocaleDateString("tr-TR")}</time></header><RichText value={a.body}/>{a.review_note&&<div><h3>İnceleme yanıtı</h3><RichText value={a.review_note}/></div>}</article>)}</div></details>}
 {(embedded||active==="appeal")&&<details open={active==="appeal"}><summary>Disiplin kararına itiraz</summary>{(eligible.length?<form className="disciplineRequestForm" action="/api/moderation/appeal" method="post"><Input type="hidden" name="return_to" value="/disiplin?tab=requests#discipline-requests"/><label>İtiraz edilecek karar<Select name="action_id" required defaultValue=""><option value="" disabled>Hakkındaki bir kararı seç</option>{eligible.map(a=><option key={a.id} value={a.id}>{new Date(a.created_at).toLocaleDateString("tr-TR")} · {a.action} · {a.id.slice(0,8)}</option>)}</Select></label><details><summary>Karar gerekçelerini oku</summary>{eligible.map(a=><article key={a.id}><h3>{new Date(a.created_at).toLocaleDateString("tr-TR")} · {a.id.slice(0,8)}</h3><RichText value={a.reason}/></article>)}</details><div className="qgEditorField"><span>İtiraz gerekçesi</span><RichTextEditor label="İtiraz gerekçesi" name="appeal" minLength={10} maxLength={1500} required/></div><Button level="primary" type="submit" className="qgAction">İTİRAZ GÖNDER</Button></form>:<p className="notice">İtiraza açık bir kararın bulunmuyor. Daha önce gönderdiğin itirazları Başvurularım bölümünden takip edebilirsin.</p>)}</details>}
 </section>;
}
