"use client";
import {useState} from "react";
import {Button,Input} from "@/components/ui/Primitives";
import type {LegacyEvent,previewEventImport} from "@/lib/event-import";
type Preview=ReturnType<typeof previewEventImport>;
const issueLabel:Record<string,string>={deleted:"Silinmiş · aktarılmayacak",duplicate_source:"Tekrarlanan kaynak kimliği",invalid_date:"Tarih geçersiz",completion_review:"Tamamlanma doğrulaması gerekli",invalid_rollcall:"Yoklama biçimi geçersiz",attendance_review:"Yoklama doğrulaması bekleyen kişiler var",legacy_type_preserved:"Eski tür adı korunacak",future_event:"Gelecekteki tarih · arşive alınmaz"};
export function EventArchiveImport() {
 const [events,setEvents]=useState<LegacyEvent[]>([]),[rows,setRows]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[confirm,setConfirm]=useState(false);
 async function preview(file:File|undefined) {
  setRows(null);setEvents([]);setConfirm(false);setNotice("");if(!file)return;
  if(file.size>200000){setNotice("Dosya çok büyük; en fazla 100 kayıtla bölerek aktar.");return;}
  setBusy(true);try{const source=JSON.parse(await file.text());const value=source.events;if(!Array.isArray(value))throw Error();const r=await fetch("/api/events/archive",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({events:value})});const data=await r.json();if(!r.ok)throw Error(data.error);setEvents(value);setRows(data.rows);}catch(e){setNotice(e instanceof Error&&e.message?e.message:"Önizleme oluşturulamadı.")}finally{setBusy(false)}
 }
 async function save(){if(!confirm||!rows)return;setBusy(true);setNotice("");try{const r=await fetch("/api/events/archive",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({events,confirm:true})});const data=await r.json();if(!r.ok)throw Error(data.error);setNotice(`${data.count} yeni etkinlik aktarıldı. Önceden aktarılmış kayıtlar tekrar oluşturulmadı.`);setConfirm(false);setRows(null);setEvents([]);}catch(e){setNotice(e instanceof Error?e.message:"Aktarım tamamlanamadı.")}finally{setBusy(false)}}
 return <details className="managementPanel eventExpand"><summary>Tarihsel Etkinlik Aktarımı</summary><p>Wix önizleme dosyasını seç. Silinmiş ve tamamlanması belirsiz kayıtlar aktarılmaz. Yoklaması bulunmayan katılımlar doğrulama bekler; eski puanlar işlenmez.</p><label className="eventUpload">Etkinlik önizleme JSON dosyası<Input type="file" accept="application/json,.json" disabled={busy} onChange={e=>preview(e.target.files?.[0])}/></label>{notice&&<p role="status" className="notice">{notice}</p>}{busy&&<p role="status">İşleniyor…</p>}{rows&&<><div className="eventImportList">{rows.map((r,i)=><article key={`${r.source_id}:${i}`} className="eventProposal"><b>{r.date} · {r.legacy_type||r.type_id}</b><p>{r.eligible?"Aktarılabilir":"İnceleme gerekiyor; aktarılmayacak"}</p><ul>{r.problems.map(p=><li key={p}>{issueLabel[p]||p}</li>)}</ul><details><summary>Üye eşleştirmeleri ({r.participants.length})</summary><ul>{r.participants.map(p=><li key={p.name}>{p.name} · {p.match==="verified_link"?"Önceden doğrulanmış üye kimliği":p.match==="candidate"?"Aday eşleşme · manuel onay gerekli":p.match==="ambiguous"?"Birden fazla aday": "Hesap eşleşmesi yok"} · {p.attended===null?"Yoklama bekliyor":p.attended?"Eski yoklamada katıldı":"Eski yoklamada katılmadı"}</li>)}</ul></details></article>)}</div><label className="eventConfirmation"><input type="checkbox" checked={confirm} disabled={busy} onChange={e=>setConfirm(e.target.checked)}/> Önizlemeyi inceledim. {rows.filter(r=>r.eligible).length} etkinliğin arşive aktarımını onaylıyorum.</label><Button type="button" level="primary" disabled={!confirm||busy||!rows.some(r=>r.eligible)} onClick={save}>Arşive Aktar</Button></>}</details>;
}
