"use client";
import {useEffect,useRef,useState} from "react";

type Props={file:File;kind:"avatar"|"banner";onCancel:()=>void;onDone:(file:File,preview:string)=>void};
export function ImageCropper({file,kind,onCancel,onDone}:Props){
 const img=useRef<HTMLImageElement|null>(null),drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
 const [src,setSrc]=useState(""),[ready,setReady]=useState(false),[zoom,setZoom]=useState(1),[offset,setOffset]=useState({x:0,y:0});
 const ratio=kind==="avatar"?1:3.8;
 useEffect(()=>{const u=URL.createObjectURL(file);setSrc(u);return()=>URL.revokeObjectURL(u)},[file]);
 const frame=()=>{const el=img.current;if(!el)return null;const w=kind==="avatar"?420:760,h=w/ratio;const base=Math.max(w/el.naturalWidth,h/el.naturalHeight),scale=base*zoom;return{w,h,scale,iw:el.naturalWidth*scale,ih:el.naturalHeight*scale}};
 const clamp=(x:number,y:number,z=zoom)=>{const el=img.current;if(!el)return{x,y};const w=kind==="avatar"?420:760,h=w/ratio,base=Math.max(w/el.naturalWidth,h/el.naturalHeight),iw=el.naturalWidth*base*z,ih=el.naturalHeight*base*z;return{x:Math.max(-(iw-w)/2,Math.min((iw-w)/2,x)),y:Math.max(-(ih-h)/2,Math.min((ih-h)/2,y))}};
 const move=(e:React.PointerEvent)=>{if(!drag.current)return;const d=drag.current;setOffset(clamp(d.ox+e.clientX-d.x,d.oy+e.clientY-d.y))};
 const finish=()=>{drag.current=null};
 const apply=()=>{const el=img.current,f=frame();if(!el||!f)return;const outW=kind==="avatar"?900:1900,outH=Math.round(outW/ratio),canvas=document.createElement("canvas");canvas.width=outW;canvas.height=outH;const ctx=canvas.getContext("2d");if(!ctx)return;const k=outW/f.w,dx=(f.w-f.iw)/2+offset.x,dy=(f.h-f.ih)/2+offset.y;ctx.drawImage(el,dx*k,dy*k,f.iw*k,f.ih*k);canvas.toBlob(blob=>{if(!blob)return;const cropped=new File([blob],kind+"-"+Date.now()+".webp",{type:"image/webp"});onDone(cropped,URL.createObjectURL(blob))},"image/webp",.9)};
 return <div className="cropOverlay" role="dialog" aria-modal="true" aria-label={kind==="avatar"?"Profil resmi kırp":"Banner kırp"}><div className="cropSheet"><header><div><small>Q-GANG · GÖRSEL DÜZENLE</small><h3>{kind==="avatar"?"Profil Resmini Kırp":"Bannerı Kırp"}</h3></div><button type="button" onClick={onCancel}>×</button></header><div className={"cropStage "+kind} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish} onPointerLeave={finish}><div className="cropFrame" style={{aspectRatio:String(ratio)}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y}}}>{src&&<img ref={img} src={src} alt="" draggable={false} onLoad={()=>setReady(true)} style={ready&&frame()?{width:frame()!.iw,height:frame()!.ih,transform:`translate(calc(-50% + ${offset.x}px),calc(-50% + ${offset.y}px))`}:undefined}/>}<span className="cropGuide"/></div></div><label className="cropZoom"><span>UZAK</span><input type="range" min="1" max="3" step=".01" value={zoom} onChange={e=>{const z=Number(e.target.value);setZoom(z);setOffset(o=>clamp(o.x,o.y,z))}}/><span>YAKIN</span></label><p>Görseli sürükleyerek kadrajı ayarla. Yakınlaştırmak için kaydırıcıyı kullan.</p><footer><button type="button" onClick={onCancel}>VAZGEÇ</button><button type="button" className="primary" disabled={!ready} onClick={apply}>KIRPMAYI UYGULA</button></footer></div></div>
}