import {Button,Input,Select} from "@/components/ui/Primitives";
import {OverflowMenu} from "@/components/ui/OverflowMenu";
import {MemberPicker} from "@/components/MemberPicker";
import {createClient,getCurrentUser} from "@/lib/supabase/server";
import {hasPermission} from "@/lib/access";
import {canAssign,canManage as canManageRole,roleLabel} from "@/lib/roles";
export async function MemberAuthorityControls({targetId}:{targetId:string}){
 const user=await getCurrentUser();if(!user||!await hasPermission(user.id,"members.manage"))return null;
 const s=await createClient();const {data:me}=await s.from("profiles").select("role").eq("id",user.id).maybeSingle();
 const {data:p}=await s.from("profiles").select("id,role,display_name").eq("id",targetId).maybeSingle();
 if(!me||!p||!canManageRole(me.role)||(p.id!==user.id&&!canAssign(me.role,p.role)))return null;
 const [{data:membership},{data:badgeCatalog},{data:manager}]=await Promise.all([s.from("community_memberships").select("status").eq("user_id",p.id).maybeSingle(),s.from("badges").select("id,name,award_mode,norm_type").eq("active",true).order("sort_order"),s.rpc("badge_manager_data")]);
 const active=membership?.status==="active",canManage=true,badgeAwards=manager?.awards??[],canChange=p.id!==user.id&&canAssign(me.role,p.role);
 return <div className="memberAuthorityControls"><section className="panel"><h2>Üyelik ve Yetki</h2><p>{active?"Aktif topluluk üyeliği":"Pasif / platform hesabı"} · {roleLabel(p.role)}</p>
 {canChange&&active&&<form action="/api/roles" method="post"><input type="hidden" name="target_id" value={p.id}/><label>Rütbe<Select name="role" defaultValue={p.role}>{["admin","moderator","creator","member"].filter(role=>canAssign(me.role,role)).map(role=><option key={role} value={role}>{roleLabel(role)}</option>)}</Select></label><label className="authorityConfirm"><input type="checkbox" required/> Rütbe değişikliğini onaylıyorum.</label><Button type="submit">Rolü Güncelle</Button></form>}
 {canChange&&<details><summary className="qgAction">{active?"Üyeliği Pasife Al":"Üyeliği Aktifleştir"}</summary><form action="/api/community-membership" method="post"><input type="hidden" name="target_id" value={p.id}/><input type="hidden" name="action" value={active?"deactivate":"activate"}/><p>{active?"Pasifleştirme topluluk erişimini kapatır ve rütbeyi platform hesabına çevirir.":"Bu hesap topluluk erişimi kazanacak."}</p><label className="authorityConfirm"><input type="checkbox" required/> {p.display_name} için bu üyelik işlemini onaylıyorum.</label><Button type="submit" level={active?"destructive":"primary"}>İşlemi Onayla</Button></form></details>}
 </section><section className="panel"><h2>Rozetler</h2>{active&&<div className="memberBadgeStrip">{(badgeAwards??[]).filter((a:any)=>a.user_id===p.id&&!a.revoked_at).map((a:any)=><div className="memberBadgeChip" key={a.id}>{a.badges?.image_url?<img src={a.badges.image_url} alt=""/>:<i>{a.badges?.icon||"✦"}</i>}<b>{a.badges?.name}</b>{canManage&&(me.role==="founder"||(["discretionary","high_honor"].includes(a.badges?.norm_type)&&a.granted_role==="admin"))&&(me.role==="founder"||a.badges?.norm_type!=="high_honor")&&<OverflowMenu label="Rozet kaydı işlemleri"><form action="/api/badges" method="post"><input type="hidden" name="action" value={a.badges?.norm_type==="historical"||a.badges?.norm_type==="achievement"?"correct":"revoke"}/><input type="hidden" name="award_id" value={a.id}/><input type="hidden" name="target_id" value={p.id}/><Input aria-label="İşlem gerekçesi" name="reason" required minLength={3} maxLength={2000} placeholder="İşlem gerekçesi"/>{["historical","achievement"].includes(a.badges?.norm_type)&&<Input aria-label="İşlem dayanağı" name="evidence" required minLength={3} maxLength={2000} placeholder="Hatalı kaydın dayanağı"/>}<label className="authorityConfirm"><input type="checkbox" required/> Rozet kaydını geri alma / düzeltme işlemini onaylıyorum.</label><Button level="destructive" type="submit" title="Rozet kaydını güncelle">GERİ AL / DÜZELT</Button></form></OverflowMenu>}</div>)}</div>}{canManage&&active&&<form className="memberBadgeAward" action="/api/badges" method="post"><input type="hidden" name="action" value="award"/><input type="hidden" name="target_id" value={p.id}/><Select aria-label="Rozet" name="badge_id" required defaultValue=""><option value="" disabled>Rozet tevcih et…</option>{(badgeCatalog??[]).filter((b:any)=>b.award_mode==="discretionary"&&(me.role==="founder"||b.norm_type!=="high_honor")&&!(badgeAwards??[]).some((a:any)=>a.user_id===p.id&&a.badge_id===b.id&&!a.revoked_at)).map((b:any)=><option value={b.id} key={b.id}>{b.name}</option>)}</Select><Input aria-label="İşlem gerekçesi" name="reason" required minLength={3} maxLength={2000} placeholder="Verilme gerekçesi"/><MemberPicker name="proposer_id" label="Teklif eden Kaptan" scope="captains" required={false}/><Button type="submit" level="secondary">VER</Button></form>}{!active&&<p>Rozet tevzihi için aktif topluluk üyeliği gerekir.</p>}</section></div>;
}
