"use client";
import {RichTextEditor} from "@/components/RichTextEditor";
import {ImageCropper} from "@/components/ImageCropper";
import {useEffect,useRef,useState} from "react";
export function ProfileEditor({profile}:{profile:any}){
 const [crop,setCrop]=useState<{file:File;kind:"avatar"|"banner"}|null>(null),[previews,setPreviews]=useState<{avatar?:string;banner?:string}>({});
 const [loading,setLoading]=useState(false),[imageError,setImageError]=useState("");
 const sources=useRef<Partial<Record<"avatar"|"banner",File>>>({}),urls=useRef<Partial<Record<"avatar"|"banner",string>>>({});
 useEffect(()=>()=>{Object.values(urls.current).forEach(url=>URL.revokeObjectURL(url))},[]);
 const editExisting=async(kind:"avatar"|"banner")=>{if(sources.current[kind]){setCrop({file:sources.current[kind]!,kind});return}const url=profile[kind+"_url"];if(!url)return;setLoading(true);setImageError("");try{const response=await fetch(url,{credentials:"omit"});if(!response.ok)throw new Error("image");const blob=await response.blob();const file=new File([blob],kind+".webp",{type:blob.type});choose(kind,file)}catch{setImageError("Mevcut görsel yüklenemedi. Tekrar dene veya yeni görsel seç.")}finally{setLoading(false)}};
 const avatarRef=useRef<HTMLInputElement>(null),bannerRef=useRef<HTMLInputElement>(null);
 const choose=(kind:"avatar"|"banner",file?:File)=>{if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)){alert("PNG, JPG veya WebP seç.");return}const max=kind==="avatar"?12:20;if(file.size>max*1024*1024){alert(`Kaynak görsel en fazla ${max} MB olabilir.`);return}sources.current[kind]=file;setImageError("");setCrop({file,kind})};
 const done=(file:File,preview:string)=>{const input=crop?.kind==="avatar"?avatarRef.current:bannerRef.current;if(input){const dt=new DataTransfer();dt.items.add(file);input.files=dt.files}const kind=crop!.kind;if(urls.current[kind])URL.revokeObjectURL(urls.current[kind]!);urls.current[kind]=preview;setPreviews(x=>({...x,[kind]:preview}));setCrop(null)};
 return <><div className="profileEditPage"><div className="profileEditSheet"><header><div><small>Q-GANG · KİMLİK</small><h2>Profili Düzenle</h2></div><a href="/profile" className="qgAction">Profile dön</a></header><form action="/api/profile" method="post" encType="multipart/form-data"><div className="profileEditGrid">{imageError&&<p className="notice profileEditWide" role="alert">{imageError}</p>}
 <label className="profileEditWide profileImageField"><span>Profil Resmi</span><div>{(previews.avatar||profile.avatar_url)&&<img className="profileCropThumb avatar" src={previews.avatar||profile.avatar_url} alt="Yeni profil resmi önizlemesi"/>}<button type="button" onClick={()=>avatarRef.current?.click()}>YENİ GÖRSEL SEÇ</button>{(previews.avatar||profile.avatar_url)&&<button type="button" disabled={loading} onClick={()=>editExisting("avatar")}>MEVCUT RESMİ DÜZENLE</button>}</div><input ref={avatarRef} hidden type="file" name="avatar" accept="image/png,image/jpeg,image/webp" onChange={e=>choose("avatar",e.target.files?.[0])}/></label>
 <label className="profileEditWide profileImageField"><span>Banner</span><div>{(previews.banner||profile.banner_url)&&<img className="profileCropThumb banner" src={previews.banner||profile.banner_url} alt="Yeni banner önizlemesi"/>}<button type="button" onClick={()=>bannerRef.current?.click()}>YENİ GÖRSEL SEÇ</button>{(previews.banner||profile.banner_url)&&<button type="button" disabled={loading} onClick={()=>editExisting("banner")}>MEVCUT BANNERI DÜZENLE</button>}</div><input ref={bannerRef} hidden type="file" name="banner" accept="image/png,image/jpeg,image/webp" onChange={e=>choose("banner",e.target.files?.[0])}/></label>
 <label className="profileEditWide">Banner Hareketi<select name="banner_motion" defaultValue={profile.banner_motion||"none"}><option value="none">Sabit</option><option value="zoom-in">Yavaş yakınlaş / uzaklaş</option><option value="zoom-out">Yavaş uzaklaş / yakınlaş</option><option value="pan-left">Yatay hareket — sağa</option><option value="pan-right">Yatay hareket — sola</option></select></label>
 <label className="profileEditWide">Profil Yorumları<select name="comments_enabled" defaultValue={profile.comments_enabled===false?"false":"true"}><option value="true">Yeni yorumlara açık</option><option value="false">Yeni yorumlara kapalı — eski yorumlar görünür</option></select></label><label>Kullanıcı Adı<input name="display_name" defaultValue={profile.display_name} required/></label><label>Rumuz<span className="fieldPrefix">@</span><input name="handle" defaultValue={profile.handle} required/></label><div className="qgEditorField"><span>Hakkında</span><RichTextEditor name="bio" maxLength={280} defaultValue={profile.bio||""} rows={5}/></div><label>Doğum Günü<input type="number" min="1" max="31" name="birthday_day" defaultValue={profile.birthday_day||""}/></label><label>Doğum Ayı<input type="number" min="1" max="12" name="birthday_month" defaultValue={profile.birthday_month||""}/></label><label>Doğum Yılı<input type="number" min="1900" max={new Date().getFullYear()} name="birthday_year" defaultValue={profile.birthday_year||""}/></label><label>Doğum Tarihi Görünürlüğü<select name="birthday_visibility" defaultValue={profile.birthday_visibility||"private"}><option value="private">Gizli</option><option value="day_month">Gün ve ay</option><option value="full">Tam tarih</option></select></label></div><footer><a href="/profile" className="qgAction">Vazgeç</a><button className="primary" type="submit">DEĞİŞİKLİKLERİ KAYDET</button></footer></form></div></div>{crop&&<ImageCropper file={crop.file} kind={crop.kind} onCancel={()=>setCrop(null)} onDone={done}/>}</>
}