"use client";
import {RichTextEditor} from "@/components/RichTextEditor";
import {ImageCropper} from "@/components/ImageCropper";
import {useRef,useState} from "react";
export function ProfileEditor({profile}:{profile:any}){
 const [open,setOpen]=useState(false),[crop,setCrop]=useState<{file:File;kind:"avatar"|"banner"}|null>(null),[previews,setPreviews]=useState<{avatar?:string;banner?:string}>({});
 const avatarRef=useRef<HTMLInputElement>(null),bannerRef=useRef<HTMLInputElement>(null);
 const choose=(kind:"avatar"|"banner",file?:File)=>{if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)){alert("PNG, JPG veya WebP seç.");return}const max=kind==="avatar"?12:20;if(file.size>max*1024*1024){alert(`Kaynak görsel en fazla ${max} MB olabilir.`);return}setCrop({file,kind})};
 const done=(file:File,preview:string)=>{const input=crop?.kind==="avatar"?avatarRef.current:bannerRef.current;if(input){const dt=new DataTransfer();dt.items.add(file);input.files=dt.files}setPreviews(x=>({...x,[crop!.kind]:preview}));setCrop(null)};
 return <>{<button className="profileInlineEdit" type="button" onClick={()=>setOpen(true)}>PROFİLİ DÜZENLE</button>}{open&&<div className="profileEditOverlay" role="dialog" aria-modal="true"><div className="profileEditSheet"><header><div><small>Q-GANG · KİMLİK</small><h2>Profili Düzenle</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></header><form action="/api/profile" method="post" encType="multipart/form-data"><div className="profileEditGrid">
 <label className="profileEditWide profileImageField"><span>Profil Resmi</span><div>{previews.avatar&&<img className="profileCropThumb avatar" src={previews.avatar} alt="Yeni profil resmi önizlemesi"/>}<button type="button" onClick={()=>avatarRef.current?.click()}>{previews.avatar?"KADRAJI DEĞİŞTİR":"GÖRSEL SEÇ VE KIRP"}</button></div><input ref={avatarRef} hidden type="file" name="avatar" accept="image/png,image/jpeg,image/webp" onChange={e=>choose("avatar",e.target.files?.[0])}/></label>
 <label className="profileEditWide profileImageField"><span>Banner</span><div>{previews.banner&&<img className="profileCropThumb banner" src={previews.banner} alt="Yeni banner önizlemesi"/>}<button type="button" onClick={()=>bannerRef.current?.click()}>{previews.banner?"KADRAJI DEĞİŞTİR":"GÖRSEL SEÇ VE KIRP"}</button></div><input ref={bannerRef} hidden type="file" name="banner" accept="image/png,image/jpeg,image/webp" onChange={e=>choose("banner",e.target.files?.[0])}/></label>
 <label>İsim Soyisim<input name="display_name" defaultValue={profile.display_name} required/></label><label>Rumuz<span className="fieldPrefix">@</span><input name="handle" defaultValue={profile.handle} required/></label><div className="qgEditorField"><span>Hakkında</span><RichTextEditor name="bio" maxLength={280} defaultValue={profile.bio||""} rows={5}/></div><label>Doğum Günü<input type="number" min="1" max="31" name="birthday_day" defaultValue={profile.birthday_day||""}/></label><label>Doğum Ayı<input type="number" min="1" max="12" name="birthday_month" defaultValue={profile.birthday_month||""}/></label><label>Doğum Yılı<input type="number" min="1900" max={new Date().getFullYear()} name="birthday_year" defaultValue={profile.birthday_year||""}/></label><label>Doğum Tarihi Görünürlüğü<select name="birthday_visibility" defaultValue={profile.birthday_visibility||"private"}><option value="private">Gizli</option><option value="day_month">Gün ve ay</option><option value="full">Tam tarih</option></select></label></div><footer><button type="button" onClick={()=>setOpen(false)}>VAZGEÇ</button><button className="primary" type="submit">DEĞİŞİKLİKLERİ KAYDET</button></footer></form></div></div>}{crop&&<ImageCropper file={crop.file} kind={crop.kind} onCancel={()=>setCrop(null)} onDone={done}/>}</>
}