import {createClient} from "@/lib/supabase/server";
import {RichTextEditor} from "@/components/RichTextEditor";
import {CommentItem} from "@/components/CommentItem";
export async function ProfileComments({profileId,handle,enabled,viewerId,page=1,feedback}:{profileId:string;handle:string;enabled:boolean;viewerId?:string|null;page?:number;feedback?:string}){
 const s=await createClient();const [{data:rows,error},{data:membership},{data:actor}]=await Promise.all([s.from("profile_comments").select("id,author_id,body,created_at,author:profiles!profile_comments_author_id_fkey(display_name,handle,avatar_url)").eq("profile_id",profileId).order("created_at",{ascending:false}).range((page-1)*10,page*10),viewerId?s.from("community_memberships").select("status").eq("user_id",viewerId).eq("status","active").maybeSingle():Promise.resolve({data:null}),viewerId?s.from("profiles").select("role").eq("id",viewerId).maybeSingle():Promise.resolve({data:null})]);
 const route=viewerId===profileId?"/profil":"/u/"+handle;
 const items=(rows??[]).map(row=>{const author=Array.isArray(row.author)?row.author[0]:row.author;return <CommentItem key={row.id} id={row.id} body={row.body} createdAt={row.created_at} author={author} canDelete={!!viewerId&&(viewerId===profileId||viewerId===row.author_id||["founder","admin"].includes(actor?.role||""))} action="/api/profile-comment" returnTo={route}/>});
 return <section className="playerPanel profileComments"><div className="playerPanelHead"><div><small>TOPLULUK</small><h2>Profil Yorumları</h2></div><span>{enabled?"YORUMLAR AÇIK":"YENİ YORUMLARA KAPALI"}</span></div>{feedback&&<p role="status">{feedback}</p>}{error?<p role="alert">Yorumlar yüklenemedi.</p>:<>{items.slice(0,5)}{items.length>5&&<details><summary>Önceki yorumları göster</summary>{items.slice(5,10)}</details>}{page>1&&<a href={route+"?comments_page="+(page-1)} className="qgAction">Önceki yorumlar</a>}{items.length>10&&<a href={route+"?comments_page="+(page+1)} className="qgAction">Daha eski yorumlar</a>}{!items.length&&<p className="muted">Henüz yorum yok.</p>}</>}{enabled&&membership&&viewerId!==profileId&&<form className="profileCommentComposer" action="/api/profile-comment" method="post"><input type="hidden" name="profile_id" value={profileId}/><input type="hidden" name="return_to" value={route}/><RichTextEditor name="body" required minLength={2} maxLength={500} rows={3} placeholder="Bir yorum bırak…" compact/><div className="commentComposerActions"><button className="qgAction commentSubmit"><span aria-hidden="true">➤</span> Yorum gönder</button></div></form>}</section>;
}
