"use client";
import {useMemo,useState} from "react";
import Link from "next/link";

type Entry={id:string;source:"publication"|"announcement";kind:string;title:string;excerpt:string;date:string|null;cover?:string|null;slug?:string|null;author:string;reading?:number|null;pinned?:boolean;priority?:string|null};
const cats=[["all","Tümü","▦"],["DUYURU","Duyurular","◈"],["KARAR","Kararlar","§"],["research","Araştırmalar","⌑"],["review","İncelemeler","▤"],["thought","Düşünceler","◯"],["game","Oyun","◇"],["technology","Teknoloji","▣"],["video","Video","▷"]] as const;
const labels:Record<string,string>={research:"ARAŞTIRMA",review:"İNCELEME",thought:"DÜŞÜNCE",game:"OYUN",technology:"TEKNOLOJİ",video:"VİDEO",DUYURU:"DUYURU",KARAR:"KARAR"};
export function PublicationsWorkspace({entries}:{entries:Entry[]}){
 const [cat,setCat]=useState("all"),[sort,setSort]=useState<"new"|"old">("new"),[q,setQ]=useState("");
 const counts=useMemo(()=>Object.fromEntries(cats.map(([k])=>[k,k==="all"?entries.length:entries.filter(x=>x.kind===k).length])),[entries]);
 const shown=useMemo(()=>entries.filter(x=>(cat==="all"||x.kind===cat)&&(!q.trim()||(x.title+" "+x.excerpt+" "+x.author).toLocaleLowerCase("tr").includes(q.trim().toLocaleLowerCase("tr")))).sort((a,b)=>(new Date(b.date||0).getTime()-new Date(a.date||0).getTime())*(sort==="new"?1:-1)),[entries,cat,q,sort]);
 return <><nav className="pubCategories" aria-label="Yayın kategorileri">{cats.map(([key,label,icon])=><button key={key} className={cat===key?"active":""} onClick={()=>setCat(key)}><b>{icon}</b><span>{label}<small>{counts[key]} yayın</small></span></button>)}</nav><div className="pubTools"><div><button className={sort==="new"?"active":""} onClick={()=>setSort("new")}>En yeni</button><button className={sort==="old"?"active":""} onClick={()=>setSort("old")}>En eski</button></div><label><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Yayınlarda ara..." aria-label="Yayınlarda ara"/></label></div><section className="pubGrid">{shown.map(e=>{const official=e.source==="announcement";const body=<><div className={"pubMedia "+(official?"officialMedia":"")}>{e.cover?<img src={e.cover} alt=""/>:<span>{e.kind==="KARAR"?"§":e.kind==="DUYURU"?"Q-GANG":labels[e.kind]?.slice(0,1)||"Q"}</span>}<strong className={"pubBadge pubBadge-"+e.kind.toLowerCase()}>{labels[e.kind]||"YAYIN"}</strong>{e.pinned&&<i className="pubPin">◆</i>}</div><div className="pubCardBody"><h2>{e.title}</h2><p>{e.excerpt}</p><footer><span>{e.author}</span><span>{e.reading?e.reading+" dk · ":""}{e.date?new Date(e.date).toLocaleDateString("tr-TR"):""}</span></footer></div></>;return e.slug?<Link href={"/yayinlar/"+e.slug} key={e.id} className={"pubCard pub-"+e.kind.toLowerCase()}>{body}</Link>:<article key={e.id} className={"pubCard pub-"+e.kind.toLowerCase()}>{body}</article>})}{!shown.length&&<div className="pubEmpty"><h2>{entries.length?"Bu filtrede yayın yok.":"Arşiv hazırlanıyor."}</h2><p>{entries.length?"Başka bir kategori seçebilir veya aramayı temizleyebilirsin.":"İlk yayın yayımlandığında burada görünecek."}</p></div>}</section></>
}