import {createClient} from "@/lib/supabase/server";
import {RichTextEditor} from "@/components/RichTextEditor";
import {CommentItem} from "@/components/CommentItem";
export async function PublicationComments({publicationId,slug,authorId,viewerId,page=1,feedback}:{publicationId:string;slug:string;authorId:string;viewerId?:string|null;page?:number;feedback?:string}){
 const s=await createClient();const [{data:rows,error},{data:membership},{data:actor}]=await Promise.all([s.from("publication_comments").select("id,author_id,body,created_at,author:profiles!publication_comments_author_id_fkey(display_name,handle,avatar_url)").eq("publication_id",publicationId).order("created_at",{ascending:false}).order("id",{ascending:false}).range((page-1)*10,page*10),viewerId?s.from("community_memberships").select("status").eq("user_id",viewerId).eq("status","active").maybeSingle():Promise.resolve({data:null}),viewerId?s.from("profiles").select("role").eq("id",viewerId).maybeSingle():Promise.resolve({data:null})]);
 const route="/yayinlar/"+slug;
 const items=(rows??[]).map(row=>{const author=Array.isArray(row.author)?row.author[0]:row.author;return <CommentItem key={row.id} id={row.id} body={row.body} createdAt={row.created_at} author={author} canDelete={!!viewerId&&(viewerId===authorId||viewerId===row.author_id||["founder","admin"].includes(actor?.role||""))} action="/api/publication-comment" returnTo={route}/>});
 return <section id="publication-comments" className="playerPanel profileComments"><div className="playerPanelHead"><div><h2>Yorumlar</h2></div></div>{feedback&&<p role="status">{feedback}</p>}{error?<p role="alert">Yorumlar yüklenemedi.</p>:<>{items.slice(0,5)}{items.length>5&&<details><summary>Önceki yorumları göster</summary>{items.slice(5,10)}</details>}{page>1&&<a href={route+"?comments_page="+(page-1)} className="qgAction">Önceki yorumlar</a>}{items.length>10&&<a href={route+"?comments_page="+(page+1)} className="qgAction">Daha eski yorumlar</a>}{!items.length&&<p className="muted">Henüz yorum yok.</p>}</>}{membership&&viewerId&&<form className="profileCommentComposer" action="/api/publication-comment" method="post"><input type="hidden" name="publication_id" value={publicationId}/><input type="hidden" name="return_to" value={route}/><RichTextEditor name="body" required minLength={2} maxLength={500} rows={3} placeholder="Bir yorum bırak…" compact/><button className="qgAction">Yorum gönder</button></form>}</section>;
}
