import {EventActionForm} from "@/components/EventActionForm";
import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {AppShell} from "@/components/AppShell";
import {EventForm} from "@/components/EventForm";
import {MemberPicker} from "@/components/MemberPicker";
import {Button,EmptyState} from "@/components/ui/Primitives";
import {createClient} from "@/lib/supabase/server";
import {getPermissions,allows} from "@/lib/permissions";
import {eventDate} from "@/lib/events";
export const dynamic="force-dynamic";
export default async function EventDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{saved?:string}>}) {
 const {user,permissions}=await getPermissions();if(!user)redirect("/login?next=/etkinlikler");
 if(!allows(permissions,"events.view"))return <AppShell right={false}><EmptyState title="Etkinliklere erişim yetkin yok"/></AppShell>;
 const {id}=await params;if(!/^[0-9a-f-]{36}$/i.test(id))notFound();const s=await createClient();
 const {data:e}=await s.from("community_events").select("*,organizer:profiles!community_events_organizer_id_fkey(display_name,handle)").eq("id",id).maybeSingle();if(!e)notFound();
 const manage=allows(permissions,"events.manage"),attendance=allows(permissions,"events.attendance");
 const [{data:types},{data:awards},{data:responses},{data:summary}]=await Promise.all([
 s.from("event_types").select("id,name,active").order("sort_order"),
 s.from("event_attendance").select("id,attended,historical_name,user_id,member:profiles!event_attendance_user_id_fkey(display_name,handle)").eq("event_id",id),
 s.from("event_responses").select("response").eq("event_id",id).eq("user_id",user.id).maybeSingle(),
 e.status!=="draft"?s.rpc("event_response_summary",{p_event:id}):Promise.resolve({data:null})]);
 const counts=summary?.[0];const saved=(await searchParams).saved;
 return <AppShell right={false}><div className="eventsPage"><section className="managementHero"><span className="kicker">Q-GANG · {types?.find(t=>t.id===e.type_id)?.name||e.legacy_type}</span><h1>{e.title}</h1><p>{eventDate(e.starts_at,e.date_only)}{!e.date_only&&` — ${eventDate(e.ends_at)}`}</p></section>
 {saved&&<p className="notice" role="status">Kayıt güncellendi.</p>}
 <section className="managementPanel eventDetail"><p className="eventDescription">{e.description}</p>{e.location&&<p><b>Buluşma:</b> {e.location}</p>}{e.organizer&&<p><b>Düzenleyen:</b> {e.organizer.display_name||e.organizer.handle}</p>}<p><b>Durum:</b> {({draft:"Taslak",published:"Yayımlandı",completed:"Tamamlandı",cancelled:"İptal edildi"})[e.status as "draft"]}</p>{counts&&<p>{counts.going} katılım yanıtı{e.capacity&&` / ${e.capacity} kişilik kapasite`}{counts.waiting>0&&` · ${counts.waiting} kişi bekleme sırasında`}</p>}
 {e.status==="published"&&new Date(e.starts_at)>new Date()&&<EventActionForm className="eventResponse"><input type="hidden" name="action" value="respond"/><input type="hidden" name="id" value={id}/><label>Katılım yanıtın<select name="response" className="qgSelect" defaultValue={responses?.response||"maybe"}><option value="going">Katılacağım</option><option value="maybe">Belki</option><option value="not_going">Katılmayacağım</option></select></label><Button level="primary" type="submit">Yanıtı Kaydet</Button>{counts?.my_waiting&&<p role="status">Bekleme sırasındasın. Yer açıldığında sıran korunarak katılım listesine geçersin.</p>}<small>Yanıtın gerçek katılım kaydı değildir; yoklama ayrıca doğrulanır.</small></EventActionForm>}</section>
 {e.status==="completed"&&<section className="managementPanel"><h2>Katılım Arşivi</h2><ul className="eventAttendance">{(awards??[]).filter(a=>a.attended).map(a=>{const member=Array.isArray(a.member)?a.member[0]:a.member;return <li key={a.id}>{member?.handle?<Link href={`/u/${member.handle}`}>{member.display_name||member.handle}</Link>:a.historical_name||"Tarihsel üye"}</li>})}</ul>{!awards?.some(a=>a.attended)&&<p className="muted">Henüz doğrulanmış katılım yok.</p>}</section>}
 {manage&&<details className="managementPanel eventExpand"><summary>Etkinliği Düzenle</summary><EventForm event={e} types={(types??[]).filter(t=>t.active||t.id===e.type_id)}/></details>}
 {manage&&allows(permissions,"events.publish")&&<details className="managementPanel eventExpand"><summary>Yayın ve Durum Yönetimi</summary><EventActionForm className="eventForm"><input type="hidden" name="action" value="status"/><input type="hidden" name="id" value={id}/><label>Yeni durum<select name="status" className="qgSelect" defaultValue={e.status}><option value="draft">Taslak</option><option value="published">Yayımla</option><option value="completed">Tamamlandı</option><option value="cancelled">İptal Et</option></select></label><label className="eventConfirmation"><input type="checkbox" name="confirm" value="yes" required/> Etkinliğin durumunu değiştirmeyi onaylıyorum.</label><Button type="submit">Durumu Kaydet</Button></EventActionForm></details>}
 {attendance&&["published","completed"].includes(e.status)&&new Date(e.starts_at)<=new Date()&&<details className="managementPanel eventExpand"><summary>Yoklama ve Katılım Doğrulama</summary><p>Yalnız gerçekleşmiş katılımı doğrula. Yanlış kaydı aynı üye için “Katılmadı” seçerek düzelt.</p><EventActionForm className="eventForm"><input type="hidden" name="action" value="attendance"/><input type="hidden" name="id" value={id}/><MemberPicker name="user_id" label="Üye" scope="events"/><label>Yoklama<select name="attended" className="qgSelect"><option value="yes">Katıldı</option><option value="no">Katılmadı / kaydı düzelt</option></select></label><label className="eventConfirmation"><input type="checkbox" name="confirm" required value="yes"/> Yoklama kaydını doğruluyorum.</label><Button type="submit" level="primary">Yoklamayı Kaydet</Button></EventActionForm><ul>{(awards??[]).map(a=>{const member=Array.isArray(a.member)?a.member[0]:a.member;return <li key={a.id}>{member?.display_name||a.historical_name} · {a.attended===null?"Doğrulama bekliyor":a.attended?"Katıldı":"Katılmadı"}</li>})}</ul></details>}
 {allows(permissions,"events.archive")&&(awards??[]).some(a=>a.historical_name)&&<details className="managementPanel eventExpand"><summary>Tarihsel Üye Eşleştirmeleri</summary>{(awards??[]).filter(a=>a.historical_name).map(a=><EventActionForm className="eventForm" key={a.id}><input type="hidden" name="action" value="link"/><input type="hidden" name="id" value={id}/><input type="hidden" name="attendance_id" value={a.id}/><p className="eventFormWide">Eski rumuz: <b>{a.historical_name}</b>{a.user_id?" · Hesaba bağlı":" · Eşleşme bekliyor"}</p><MemberPicker name="user_id" scope="events" label="Doğrulanan hesap"/><label className="eventConfirmation"><input type="checkbox" name="confirm" value="yes" required/> Bu hesabın tarihsel üyeye ait olduğunu doğruladım.</label><Button type="submit">Kimliği Eşleştir</Button></EventActionForm>)}</details>}
 <Link className="qgButton qgButton-tertiary" href="/etkinlikler">← Etkinliklere Dön</Link></div></AppShell>;
}
