const fs=require('fs'),vm=require('vm'),ts=require('typescript'),assert=require('node:assert/strict');
function load(file,dependencies={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Date,Set,Map,JSON,require:n=>dependencies[n]??require(n)});return exports}
const events=load('src/lib/events.ts'),imports=load('src/lib/event-import.ts',{'@/lib/events':events});
assert.deepEqual(Array.from(events.EVENT_TYPES,x=>x.name),['GANG-UP','OP-NIGHT','BBQ-GANG','Q-NITY']);assert.equal(events.istanbulInput('2026-10-08T19:30'),'2026-10-08T16:30:00.000Z');assert.equal(events.istanbulInput('2026-02-30T19:30'),null);assert.equal(events.eventDays('2026-10-08T21:00:00Z',new Date('2026-10-07T22:00:00Z')),1);
const rows=[{id:'one',type:'OP-NIGHT',date:'2026-01-01',status:'puan_onaylandi',names:' @Alpha ,alpha,Beta,Gamma',attendance:'{"Alpha":"present","Beta":"absent"}',attendanceConfirmed:true},{id:'deleted',type:'OP-NIGHT',date:'2026-01-01',deleted:true,status:'completed'},{id:'legacy',type:'B-DAY & S-DAY',date:'2026-01-01',status:'completed',names:'Alpha'},{id:'one',type:'GANG-UP',date:'2026-01-01',status:'completed'},{id:'invalid',type:'GANG-UP',date:'2026-02-30',status:'completed'},{id:'pending',type:'OP-NIGHT',date:'2026-01-01',status:'taslak'},{id:'future',type:'OP-NIGHT',date:'2099-01-01',status:'completed'}];
const profiles=[{id:'a',handle:'alpha',display_name:'Alpha'},{id:'b',handle:'beta',display_name:'Beta'},{id:'c',handle:'other',display_name:'Beta'}];const preview=imports.previewEventImport(rows,profiles,[{name:'Alpha',user_id:'a'}]);
assert.equal(preview[0].participants.length,3);assert.equal(preview[0].participants[0].user_id,'a');assert.equal(preview[0].participants[0].attended,true);assert.equal(preview[0].participants[1].match,'ambiguous');assert.equal(preview[0].participants[1].user_id,null);assert.equal(preview[0].participants[2].match,'unmatched');assert.equal(preview[0].participants[2].attended,null);assert.equal(preview[1].eligible,false);assert.equal(preview[2].legacy_type,'B-DAY & S-DAY');assert.equal(preview[2].type_id,null);assert.equal(preview[2].participants[0].attended,null);for(let i=3;i<7;i++)assert.equal(preview[i].eligible,false);
if(process.argv[2]){const inventory=JSON.parse(fs.readFileSync(process.argv[2])),matching=JSON.parse(fs.readFileSync(process.argv[3]));const p=imports.previewEventImport(inventory.events,matching.profiles,matching.links);const participants=p.filter(e=>e.eligible).flatMap(e=>e.participants);console.log(JSON.stringify({records:p.length,eligible:p.filter(e=>e.eligible).length,deleted:p.filter(e=>e.problems.includes('deleted')).length,legacyTypes:p.filter(e=>e.legacy_type&&!e.problems.includes('deleted')).length,participations:participants.length,verifiedIdentity:participants.filter(p=>p.match==='verified_link').length,unmatched:participants.filter(p=>p.match==='unmatched').length,verifiedAttendance:participants.filter(p=>p.attended===true).length,pendingAttendance:participants.filter(p=>p.attended===null).length},null,2))}
console.log('PASS events domain: type order, Istanbul dates, invalid/future dates, deleted/draft/duplicate records, verified identity links, ambiguous/unmatched names and independent attendance.');
