-- Badge System 1.0; extends the legacy badge tables.
alter table public.badges add column if not exists category text not null default 'contribution', add column if not exists award_mode text not null default 'discretionary', add column if not exists image_url text, add column if not exists active boolean not null default true, add column if not exists sort_order integer not null default 0, add column if not exists rule jsonb not null default '{}'::jsonb, add column if not exists updated_at timestamptz not null default now();
alter table public.profile_badges add column if not exists reason text, add column if not exists revoked_at timestamptz, add column if not exists revoked_by uuid references public.profiles(id) on delete set null, add column if not exists revoke_reason text, add column if not exists source text not null default 'manual';
create unique index if not exists profile_badges_one_active on public.profile_badges(user_id,badge_id) where revoked_at is null;
alter table public.badges enable row level security; alter table public.profile_badges enable row level security; grant select on public.badges to anon,authenticated; grant select on public.profile_badges to anon,authenticated; grant insert,update on public.profile_badges to authenticated;
drop policy if exists "badges public read v2" on public.badges; create policy "badges public read v2" on public.badges for select to anon,authenticated using(active=true);
drop policy if exists "profile badges public read v2" on public.profile_badges; create policy "profile badges public read v2" on public.profile_badges for select to anon,authenticated using(revoked_at is null);
drop policy if exists "management awards badges v2" on public.profile_badges; create policy "management awards badges v2" on public.profile_badges for insert to authenticated with check(source='manual' and granted_by=(select auth.uid()) and exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('founder','admin')) and exists(select 1 from public.badges b where b.id=badge_id and b.active and b.award_mode='discretionary'));
drop policy if exists "management revokes badges v2" on public.profile_badges; create policy "management revokes badges v2" on public.profile_badges for update to authenticated using(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('founder','admin'))) with check(revoked_by=(select auth.uid()) and revoked_at is not null);
insert into public.badges(slug,name,description,icon,category,award_mode,sort_order,rule) values
('ilk-halka','İlk Halka','Q-GANG’ın ilk dönemine tanıklık eden üyelerin tarihsel nişanı.','◉','honorary','historical',10,'{"kind":"foundation-era"}'),('kidem-nisani','Kıdem Nişanı','Uzun süreli ve istikrarlı topluluk üyeliğinin nişanı.','⌛','contribution','automatic',20,'{"kind":"membership-tenure","years":2}'),('muellif','Müellif','Nitelikli yayın ve araştırma üretimine katkının nişanı.','✒','contribution','automatic',30,'{"kind":"published-work","count":1}'),('mimar','Mimar','Q-GANG sistem, proje veya altyapısına kayda değer katkı.','△','contribution','discretionary',40,'{}'),('muhafiz','Muhafız','Topluluğun korunmasına özel katkı.','⬟','honorary','discretionary',50,'{}'),('yoldas','Yoldaş','Kardeşlik ve dayanışmaya özel katkı.','∞','honorary','discretionary',60,'{}'),('adalet-nisani','Adalet Nişanı','Adalet ilkesine örnek ve özel katkı.','⚖','honorary','discretionary',70,'{}'),('sadakat-nisani','Sadakat Nişanı','Uzun dönemli güven ve bağlılığın özel takdiri.','⬡','honorary','discretionary',80,'{}'),('oncu','Öncü','Yeni bir proje, alan veya format açan katkı.','✧','contribution','discretionary',90,'{}'),('liyakat-nisani','Liyakat Nişanı','Kategoriler üstü olağanüstü hizmet için yüksek onur nişanı.','✥','honorary','discretionary',100,'{}') on conflict(slug) do update set name=excluded.name,description=excluded.description,category=excluded.category,award_mode=excluded.award_mode,sort_order=excluded.sort_order,rule=excluded.rule,updated_at=now();
create or replace function public.qgang_sync_automatic_badges(target_user uuid) returns void language plpgsql security definer set search_path=public as $$ declare b uuid; begin select id into b from public.badges where slug='muellif' and active; if b is not null and exists(select 1 from public.publications where author_id=target_user and status='published') then insert into public.profile_badges(user_id,badge_id,reason,source) select target_user,b,'İlk yayımlanmış eser','automatic' where not exists(select 1 from public.profile_badges where user_id=target_user and badge_id=b and revoked_at is null); end if; select id into b from public.badges where slug='kidem-nisani' and active; if b is not null and exists(select 1 from public.community_memberships where user_id=target_user and status='active' and joined_at<=now()-interval '2 years') then insert into public.profile_badges(user_id,badge_id,reason,source) select target_user,b,'İki yıllık aktif üyelik kıdemi','automatic' where not exists(select 1 from public.profile_badges where user_id=target_user and badge_id=b and revoked_at is null); end if; end $$; revoke all on function public.qgang_sync_automatic_badges(uuid) from public,anon,authenticated;
create or replace function public.qgang_badge_publication_trigger() returns trigger language plpgsql security definer set search_path=public as $$ begin if new.status='published' then perform public.qgang_sync_automatic_badges(new.author_id); end if; return new; end $$; drop trigger if exists trg_qgang_badge_publication on public.publications; create trigger trg_qgang_badge_publication after insert or update of status on public.publications for each row execute function public.qgang_badge_publication_trigger();