import Link from "next/link";
import {PublicationStudio} from "@/components/PublicationStudio";
import {allows,getPermissions} from "@/lib/permissions";
import {richPlain} from "@/lib/rich-text";
import {PublicationsWorkspace} from "@/components/PublicationsWorkspace";
import {createClient} from "@/lib/supabase/server";
import {AppShell} from "@/components/AppShell";
import {brandTheme} from "@/config/brand-theme";
export const dynamic="force-dynamic";export const metadata={title:"Yayınlar"};
export default async function Publications({searchParams}:{searchParams:Promise<{studio?:string;edit?:string;saved?:string;deleted?:string;error?:string}>}){const q=await searchParams;const s=await createClient();const [permissionResult,publicationResult]=await Promise.all([getPermissions(),s.from("publications").select("title,slug,excerpt,cover_url,content_type,published_at,reading_minutes,youtube_url,author:profiles!publications_author_id_fkey(display_name,handle)").eq("status","published").order("published_at",{ascending:false}).limit(96)]);const {permissions}=permissionResult;const canWrite=allows(permissions,"publications.write");const {data:publications}=publicationResult;const entries=(publications??[]).map((x:any)=>{const author=Array.isArray(x.author)?x.author[0]:x.author;return{id:"p-"+x.slug,source:"publication" as const,kind:x.youtube_url?"video":x.content_type,title:x.title,excerpt:richPlain(x.excerpt||"")||"Bu yayın için henüz özet eklenmedi.",date:x.published_at,cover:x.cover_url,slug:x.slug,author:author?.display_name||author?.handle||"Q-GANG",reading:x.reading_minutes}});return <AppShell right={false}><main className="publicationIndex pubV2"><section className="publicationHero pubHeroV2 roomScene unifiedPageHero" style={{backgroundImage:`linear-gradient(90deg,rgba(4,3,2,.82),rgba(4,3,2,.42) 52%,rgba(4,3,2,.2)),url(${brandTheme.rooms.publications})`}}><small>EDİTORYAL ARŞİV</small><h1>YAYINLAR</h1><p>Araştırmalar, incelemeler, düşünceler, oyun, teknoloji ve videolar tek bir editoryal arşivde.</p></section>{canWrite&&<nav className="publicationTools" aria-label="Yayın işlemleri"><Link className="qgAction qgActionPrimary" href="/yayinlar?studio=1">+ Yeni yayın</Link><Link className="qgAction" href="/yayinlar?studio=1#publication-studio">Yayın yönetimi</Link>{q.studio&&<Link className="qgAction" href="/yayinlar">Arşive dön</Link>}</nav>}{canWrite&&q.studio?<div id="publication-studio"><PublicationStudio searchParams={Promise.resolve(q)}/></div>:<PublicationsWorkspace entries={entries}/>}</main></AppShell>}